// attractions-data.mjs
// Single source of truth for all 8 Guilin attraction detail pages.
// Consumed by scripts/build-attractions.mjs -> renders attractions/*.html
// Image names map to files already present in /images (webp + jpg pairs).

export const SITE = {
  name: 'Visit Guilin',
  url: 'https://myguilin.com',
  phone: '+86 187 7735 8302',
  whatsapp: '8618777358302',
  email: 'willyumi2026@outlook.com',
};

export const attractions = [
  /* ============================== 1. LI RIVER ============================== */
  {
    slug: 'liriver',
    name: 'Li River',
    cnName: '漓江',
    kicker: "China's Most Scenic River Journey · Guilin–Yangshuo",
    heroImage: 'hero-liriver',
    ogImage: 'hero-liriver',
    tagline: '漓江 · Where Karst Peaks Meet the Water',
    lead: 'Cruise 83 kilometers through the heart of Guilin’s otherworldly limestone landscape — the view that graces China’s 20-yuan banknote, and the journey that has inspired poets and painters for a thousand years.',
    glance: '<strong class="text-river">The Li River (漓江)</strong> flows 83&nbsp;km from Guilin to Yangshuo through one of the world’s most extraordinary karst landscapes — a UNESCO World Heritage candidate of limestone towers, bamboo groves, and water buffalo-dotted banks. The 4–5 hour cruise from Guilin to Yangshuo is the single most famous tourist journey in China, featured on the back of the ¥20 banknote.',
    intro: [
      'If Guilin has one experience that defines it, this is the one. The Li River (漓江) cuts through the world’s largest karst landscape — over 40,000 square kilometers of cone-shaped limestone peaks that rise straight from the water like a Chinese ink painting come to life. For centuries, this stretch of river has been China’s most painted, most photographed, and most written-about landscape.',
      'The classic journey runs from Guilin’s Zhujiang Pier down to Yangshuo — about <strong class="text-river">83 kilometers (4–5 hours)</strong> of floating through scenery that changes every bend: cormorant fishermen on bamboo rafts, water buffalo wading in the shallows, ancient villages tucked between sugar-loaf peaks. The view at Xingping, where the river wraps around a cluster of dramatic karst towers, is the one printed on the <strong class="text-river">¥20 Chinese banknote</strong>.',
      '<span class="text-sm text-stone-600"><em>Quick tip: the cruise is one-way downstream (Guilin → Yangshuo). Most travelers explore Yangshuo’s countryside after disembarking and return to Guilin by bus (about 90 minutes).</em></span>',
    ],
    highlights: [
      { img: 'hero-liriver', title: 'Li River Panorama', sub: '漓江 · Karst peaks from above', text: 'A sweeping aerial view of the river winding through sugar-loaf limestone towers — the classic Guilin landscape.' },
      { img: 'attraction-liriver', title: 'Xingping Riverfront', sub: '兴坪码头 · Sunset at the pier', text: 'Tour boats dock at Xingping’s waterfront as the sun sets behind the limestone towers — a quiet end to the river journey.' },
      { img: 'exp-cormorant', title: 'Cormorant Raft Scene', sub: '鸬鹚竹筏 · Li River heritage', text: 'A traditional cormorant fisherman poles a bamboo raft on the Li River, with karst peaks rising behind him — a scene rooted in centuries of local fishing culture.' },
      { img: 'web-xingping-bend', title: 'Karst Peaks above Xingping', sub: '兴坪峰丛 · The 20-yuan backdrop', text: 'The knife-sharp limestone towers that line the Li River near Xingping, the same peaks that appear on China’s ¥20 note.' },
      { img: 'exp-xianggong', title: 'Xianggong Mountain Overlook', sub: '相公山 · Sunrise panorama', text: 'A high viewpoint above the Li River catches first light on the karst towers and the river’s silver ribbon.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Full Cruise', meta: '4–5 hours · Guilin → Yangshuo · ¥300–500',
        steps: [
          { t: 'Board at Zhujiang Pier', d: '竹江码头 — about 40 min from Guilin city center.' },
          { t: 'Cruise past Crown Cave', d: '冠岩 — the first major karst formation.' },
          { t: 'Nine Horse Fresco Hill', d: 'Count the horses on the cliff.' },
          { t: '20-Yuan note view', d: 'at Xingping — the cruise slows for photos.' },
          { t: 'Disembark at Yangshuo', d: 'Explore West Street, then bus back to Guilin (90 min).' },
        ],
      },
      {
        icon: 'anchor', title: 'Bamboo Raft (Best Section)', meta: '1–1.5 hours · Xingping–Nine Horse · ¥120–255',
        steps: [
          { t: 'Get to Xingping', d: 'Take a bus from Yangshuo (40 min) or Guilin (2 hrs).' },
          { t: 'Board a 4-seat bamboo raft', d: 'at Xingping pier — motorized, stable, life jackets provided.' },
          { t: 'Glide past the 20-yuan view', d: 'and Nine Horse Hill, the most scenic section.' },
          { t: 'Return by electric cart', d: 'included in the ticket.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'Apr – May', text: 'Warm, green hillsides, light mist — the most photogenic season.' },
      { icon: 'calendar-heart', title: 'Sep – Nov', text: 'Clear skies, crisp air, golden rice fields along the banks.' },
      { icon: 'cloud-rain', title: 'After rain', text: 'Mist swirling around peaks = the classic ink-painting photos.' },
    ],
    tips: [
      { icon: 'clock', title: 'Book the morning cruise', text: 'Morning departures (8:30–9:30 AM) give the best light and the fewest crowds. Afternoon boats can feel rushed.' },
      { icon: 'sun', title: 'Bring sunscreen and a hat', text: 'The upper deck has no shade, and Guilin’s sun is strong even in spring. Sunglasses help with glare off the water.' },
      { icon: 'camera', title: 'Upper deck = best photos', text: 'Pay the small upgrade (usually ¥20–50) for the upper deck. The view is unobstructed and the breeze keeps you cool.' },
      { icon: 'utensils', title: 'The boat lunch is basic — pack snacks', text: 'Cruise lunch is a simple Chinese boxed meal. Bring your own water, fruit, and snacks for a better experience.' },
      { icon: 'droplet', title: 'Check water levels before you go', text: 'During summer floods or winter dry spells, the full cruise may be suspended and replaced by shorter raft sections. Ask locally the day before.' },
    ],
    gettingThere: [
      { t: 'From Guilin city → Zhujiang Pier', d: 'Take a taxi or pre-booked transfer (about 40 min, ¥80–120). Public bus #9 from the bus station is ¥20 but slower.' },
      { t: 'Buy tickets in advance', d: 'Cruise tickets (¥300–500 depending on boat class) can be booked through hotels, travel agencies, or online — there’s no walk-up ticket office at the pier for foreign tourists.' },
      { t: 'Board and cruise', d: '4–5 hours downstream to Yangshuo. Boats have toilets, a snack bar, and an upper viewing deck.' },
      { t: 'Return from Yangshuo', d: 'Regular buses from Yangshuo bus station to Guilin (90 min, ¥25–30). The last bus is around 18:30 — if you miss it, a taxi is about ¥150–200.' },
    ],
    tickets: [
      ['Full cruise (Guilin–Yangshuo)', '¥300–500 — includes simple lunch; 4-seat & luxury boat options'],
      ['Bamboo raft (Xingping section)', '¥120–255 — 4 people per raft; the best 1-hour highlight'],
      ['Cruise departure times', '8:30, 9:00, 9:30 AM (varies by season)'],
      ['Cruise duration', '4–5 hours (83 km downstream)'],
      ['Best months', 'April–May, September–November'],
      ['Pier location', 'Zhujiang Pier (竹江码头) — 40 min from Guilin city'],
    ],
    ticketNote: 'Prices are reference values for international travelers and may change by season. Bamboo rafts do not operate during heavy rain or flood warnings. Foreign tourists must bring a passport — it’s checked at the pier.',
    gallery: [
      { img: 'hero-liriver', alt: 'Li River winding through karst peaks' },
      { img: 'attraction-liriver', alt: 'Li River waterfront at Xingping' },
      { img: 'exp-cormorant', alt: 'Cormorant fisherman on a bamboo raft on the Li River' },
      { img: 'exp-xianggong', alt: 'Karst peaks above the Li River from Xianggong Mountain' },
      { img: 'web-liriver-village', alt: 'A riverside village along the Li River' },
      { img: 'web-yangshuo-countryside', alt: 'Cruise boats on the Li River among karst peaks' },
    ],
    faqs: [
      { q: 'How long is the Li River cruise, and where does it start and end?', a: 'The classic cruise is 83&nbsp;km (about 4–5 hours) from Zhujiang Pier outside Guilin to Yangshuo town. Boats depart between 8:30 and 9:30 AM, and you arrive in Yangshuo around 1:30–2:30 PM. Shorter bamboo raft options (1–1.5 hours) run on the Xingping section.' },
      { q: 'Is the ¥20 banknote view actually on the Li River?', a: 'Yes — absolutely. The scene on the back of China’s ¥20 note is the view near Xingping village, about two-thirds of the way down the river. The cruise slows down at this spot, and it’s also accessible from land if you take the bamboo raft instead.' },
      { q: 'What’s the difference between the full cruise and the bamboo raft?', a: 'The full cruise is a 4–5 hour motorized boat journey covering the entire river from Guilin to Yangshuo, with a simple lunch included. The bamboo raft (actually a motorized 4-seat PVC raft) covers only the most scenic 1–1.5 hour section at Xingping but gets you closer to the water and the 20-yuan view — and costs less.' },
      { q: 'Can I book the cruise ticket on the same day?', a: 'Not reliably. The pier does not have a walk-up ticket office for foreign travelers — you need to book through a hotel, travel agency, or online platform at least one day ahead, especially in peak season (Apr–May, Sep–Oct). Your hotel can almost always arrange it.' },
      { q: 'What happens if it rains? Does the cruise still run?', a: 'Light rain is fine — the cruise runs, and the misty peaks are actually more atmospheric. But during heavy flooding (usually June–July), the cruise may be suspended for safety. Bamboo rafts are the first to stop. Always check the forecast and ask locally the day before.' },
      { q: 'Should I stay in Guilin or Yangshuo after the cruise?', a: 'Yangshuo, hands down. The town is small, walkable, and surrounded by karst peaks. After the cruise, you can rent a bike (¥20–30/day) and explore the countryside villages, Yulong River paths, and Moon Hill. Most travelers spend 1–2 nights here. Guilin city is convenient for train/airport connections but doesn’t compare to Yangshuo’s atmosphere.' },
    ],
    quickFacts: [
      ['Length', '83 km'],
      ['Cruise duration', '4–5 hours'],
      ['Best season', 'Apr–May · Sep–Nov'],
      ['Route', 'Guilin → Yangshuo'],
      ['Ticket', '¥300–500'],
      ['Boat type', '3- or 4-star cruiser'],
      ['Famous for', '¥20 banknote view'],
    ],
    localTip: 'Skip the crowded 4-star boat and take the bamboo raft from Xingping instead. You’ll see the exact same 20-yuan view with fewer people, closer to the water, for half the price — then spend the rest of the day cycling through Yangshuo’s countryside.',
    related: [
      { slug: 'yangshuo', img: 'attraction-yangshuo', title: 'Yangshuo & West Street', sub: '阳朔 · Karst countryside & nightlife' },
      { slug: 'elephant', img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · Guilin’s city symbol' },
      { slug: 'longji', img: 'attraction-longji', title: 'Longji Rice Terraces', sub: '龙脊 · Dragon-back mountain rice fields' },
      { slug: 'xingping', img: 'attraction-xingping', title: 'Xingping Ancient Town', sub: '兴坪 · The 20-yuan banknote village' },
    ],
    geo: { lat: 25.07, lng: 110.32 },
  },

  /* ============================ 2. ELEPHANT TRUNK HILL ============================ */
  {
    slug: 'elephant',
    name: 'Elephant Trunk Hill',
    cnName: '象鼻山',
    kicker: "Guilin's City Symbol · On the Li River",
    heroImage: 'attraction-elephant',
    ogImage: 'attraction-elephant',
    tagline: '象鼻山 · The Elephant Drinking from the River',
    lead: 'Guilin’s most beloved landmark — a 55-meter limestone hill whose natural arch looks exactly like an elephant lowering its trunk to drink from the Li River. It’s on every postcard, and it’s even better in person at night.',
    glance: '<strong class="text-river">Elephant Trunk Hill (象鼻山)</strong> is the emblem of Guilin, sitting right at the confluence of the Li River and the Peach Blossom River in the heart of the city. The rounded hill with a water-worn arch resembles an elephant dipping its trunk into the water. A short, flat visit (1–2 hours), it’s the easiest “must-see” in town and spectacular when lit after dark.',
    intro: [
      'You’ll recognize it instantly: a bulky limestone hill with a rounded “body,” and a slender rock arch at the waterline that looks uncannily like an elephant’s trunk curling down to drink. Locals have called it Elephant Trunk Hill for over a thousand years, and it appears on everything from city logos to airline magazines.',
      'The hill sits where the <strong class="text-river">Li River meets the Peach Blossom River (桃花江)</strong>, just south of the old city center — an easy taxi or 20-minute walk from most downtown hotels. A leafy park wraps the base, with pavilions, a small cave you can walk through, and a riverside path that gives the classic photo angle.',
      '<span class="text-sm text-stone-600"><em>Quick tip: come twice if you can — by day for the green park and clear reflections, and again after dark when colored lights turn the elephant gold and the water shimmers.</em></span>',
    ],
    highlights: [
      { img: 'attraction-elephant', title: 'The Elephant Arch', sub: '象鼻 · The trunk & reflection', text: 'The natural limestone arch at the waterline is the money shot. Stand on the riverside path for the perfect “elephant drinking” silhouette with its reflection.' },
      { img: 'band-elephant', title: 'Riverside Park', sub: '象山公园 · Easy stroll', text: 'Shady walkways and gardens wrap around the hill. The flat, family-friendly park takes 1–2 hours to explore.' },
      { img: 'web-elephant-night', title: 'Elephant Hill at Night', sub: '象鼻山夜景 · Gold on the water', text: 'After dark, colored lights turn the hill golden and its reflection shimmers on the Li River.' },
      { img: 'web-tworivers-bridge', title: 'Sun & Moon Pagodas', sub: '日月双塔 · 10-min walk', text: 'A gold and a silver pagoda light up on Shanhu Lake, an easy evening add-on to Elephant Hill.' },
      { img: 'attraction-reedflute', title: 'Reed Flute Cave', sub: '芦笛岩 · 20 min away', text: 'A 180-million-year-old limestone cave with lit stalactites and an underground lake — easy to pair with Elephant Hill in one morning.' },
    ],
    routes: [
      {
        icon: 'anchor', title: 'Park Visit (Classic)', meta: '1–2 hours · Flat walk · ¥55–70',
        steps: [
          { t: 'Enter the south gate', d: 'Buy a ticket at the park entrance (¥55–70 for foreign visitors).' },
          { t: 'Walk the riverside path', d: 'To the best “elephant drinking” photo spot on the Li River side.' },
          { t: 'Pass through Water Moon Cave', d: 'The arch tunnel beneath the trunk — cool and atmospheric.' },
          { t: 'Climb to Puxian Pagoda', d: 'A short, easy rise to the hilltop for city-and-river views.' },
        ],
      },
      {
        icon: 'ship', title: 'Li River Boat Angle', meta: 'Optional · 30 min · ¥40–60',
        steps: [
          { t: 'Take a short river boat', d: 'From nearby pier, circles the hill for the postcard view from the water.' },
          { t: 'Best light', d: 'Go just before sunset for golden-hour photos and the start of the light show.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'Apr – Oct', text: 'Warm, green park, long evenings — ideal for both day and night visits.' },
      { icon: 'sun', title: 'Golden hour', text: 'Arrive 5–6 PM: clear daytime shots, then stay for the light show.' },
      { icon: 'cloud-rain', title: 'After rain', text: 'The river runs fuller and the reflections are crisp — a favorite of photographers.' },
    ],
    tips: [
      { icon: 'clock', title: 'Visit late afternoon', text: 'One ticket covers both day and night views if you arrive before the light show (around 7 PM in summer).' },
      { icon: 'camera', title: 'Shoot from the east bank', text: 'The classic “trunk drinking” composition is from the Li River side path, not the entrance.' },
      { icon: 'sun', title: 'Bring water in summer', text: 'The park is open and can be hot in July–August; mornings are cooler.' },
      { icon: 'droplet', title: 'Combine with the lakes', text: 'Elephant Hill is a 10-minute walk from the Two Rivers & Four Lakes promenade — do both in one evening.' },
      { icon: 'utensils', title: 'Snacks inside', text: 'Small cafes near the entrance sell drinks and ice cream; nothing fancy.' },
    ],
    gettingThere: [
      { t: 'From Guilin city center', d: 'A taxi takes 10–15 min (¥10–15). Many downtown hotels are a 20-minute walk away.' },
      { t: 'By bus', d: 'Several city buses stop near the south gate (e.g. routes 2, 16, 23); ask your hotel for the nearest.' },
      { t: 'On foot from the lakes', d: 'Walkable from Shanhu / Ronghu lakes along the riverside promenade (about 15 min).' },
      { t: 'Tickets', d: 'Buy at the gate or via your hotel; no advance booking needed for foreign visitors.' },
    ],
    tickets: [
      ['Entrance ticket', '¥55–70 — covers the park and hilltop pagoda'],
      ['Opening hours', 'Daylight to ~21:00 (night light show included)'],
      ['Suggested visit', '1–2 hours'],
      ['Best months', 'April–October'],
      ['Location', 'Confluence of Li River & Peach Blossom River'],
      ['Difficulty', 'Easy · flat paths'],
    ],
    ticketNote: 'Prices are reference values and may shift by season. The hill is inside a managed park; keep your ticket for re-entry if you leave for food. Evening light shows run roughly 7–9 PM in summer.',
    gallery: [
      { img: 'attraction-elephant', alt: 'Elephant Trunk Hill by day' },
      { img: 'band-elephant', alt: 'Elephant Trunk Hill park view' },
      { img: 'web-elephant-night', alt: 'Elephant Trunk Hill lit at night' },
      { img: 'web-tworivers-bridge', alt: 'Sun and Moon Pagodas near Elephant Hill' },
      { img: 'attraction-reedflute', alt: 'Reed Flute Cave near Elephant Hill' },
      { img: 'attraction-tworivers', alt: 'Sun and Moon Pagodas on Shanhu Lake' },
    ],
    faqs: [
      { q: 'How much time do I need at Elephant Trunk Hill?', a: 'About 1–2 hours for a relaxed walk through the park, the Water Moon Cave, and the hilltop pagoda. Add an hour if you stay for the night light show.' },
      { q: 'Is it worth visiting at night?', a: 'Yes. The colored lights and river reflection are genuinely beautiful, and one ticket covers both day and night if you arrive before the show starts (around 7 PM in summer).' },
      { q: 'Can I see it without buying a ticket?', a: 'The best “elephant drinking” photo is from the public riverside path outside the paid park, which is free. The ticket gets you inside the gardens, the cave, and the hilltop.' },
      { q: 'Is Elephant Trunk Hill suitable for kids and seniors?', a: 'Very much so — paths are flat and shaded, with no steep climbs except the short, optional rise to the pagoda.' },
      { q: 'How do I combine it with other sights?', a: 'It’s a 10-minute walk from the Two Rivers & Four Lakes lakes and 15 minutes from the city’s main pedestrian streets. Pair it with an evening lakes cruise.' },
      { q: 'What’s the story behind the name?', a: 'The shape of the hill — a rounded body and a slender rock arch at the water — has looked like an elephant dipping its trunk to drink for over a millennium, so the name is purely descriptive and ancient.' },
    ],
    quickFacts: [
      ['Height', '~55 m'],
      ['Visit time', '1–2 hours'],
      ['Best season', 'Apr–Oct'],
      ['Location', 'Guilin city center'],
      ['Ticket', '¥55–70'],
      ['Difficulty', 'Easy'],
      ['Famous for', 'City emblem'],
    ],
    localTip: 'Don’t just photograph it from the entrance bridge. Walk around to the Li River side — that’s the angle on every Guilin postcard, and it’s free.',
    related: [
      { slug: 'tworivers', img: 'attraction-tworivers', title: 'Two Rivers & Four Lakes', sub: '两江四湖 · Night cruise & lakes' },
      { slug: 'liriver', img: 'hero-liriver', title: 'Li River Cruise', sub: '漓江 · The iconic journey' },
      { slug: 'reedflute', img: 'attraction-reedflute', title: 'Reed Flute Cave', sub: '芦笛岩 · Underground palace' },
      { slug: 'yangshuo', img: 'attraction-yangshuo', title: 'Yangshuo & West Street', sub: '阳朔 · Countryside & nightlife' },
    ],
    geo: { lat: 25.273, lng: 110.295 },
  },

  /* ============================ 3. YANGSHUO & WEST STREET ============================ */
  {
    slug: 'yangshuo',
    name: 'Yangshuo & West Street',
    cnName: '阳朔',
    kicker: "Karst Countryside & Nightlife · 65 km from Guilin",
    heroImage: 'attraction-yangshuo',
    ogImage: 'attraction-yangshuo',
    tagline: '阳朔 · The Town Wrapped in Karst Peaks',
    lead: 'The place most travelers remember longest. Yangshuo is a small town ringed by dramatic karst peaks, with a 1,400-year-old pedestrian street (West Street) of cafes and bars — and countryside biking, rafting, and climbing right outside the door.',
    glance: '<strong class="text-river">Yangshuo (阳朔)</strong> sits about 65&nbsp;km south of Guilin, at the end of the Li River cruise. Its compact old town centers on <strong class="text-river">West Street (西街)</strong> — a cobbled pedestrian lane over 1,400 years old, now lined with cafes, guesthouses, and bars. Surrounding it are some of the most bikeable, climbable, and photogenic karst landscapes in China.',
    intro: [
      'If the Li River cruise is Guilin’s headline act, Yangshuo is the encores. The cruise drops you here, and most travelers wish they’d booked an extra night. The town is tiny and walkable, but step beyond West Street and you’re immediately among rice fields, bamboo groves, and limestone peaks that seem to rise from the earth like a studio backdrop.',
      'West Street itself is a contradiction in the best way: a genuine Tang-dynasty lane (look up — some of the old brickwork survives) now humming with espresso machines, craft beer, and English menus. It’s the most foreigner-friendly spot in the region, which is exactly why backpackers and tour groups alike converge here.',
      '<span class="text-sm text-stone-600"><em>Quick tip: stay at least one night. Days are for biking the Yulong River and climbing Moon Hill; nights are for West Street’s rooftop bars and the riverside sound-and-light show.</em></span>',
    ],
    highlights: [
      { img: 'attraction-yangshuo', title: 'West Street (西街)', sub: '千年老街 · The social heart', text: 'A 1,400-year-old pedestrian lane packed with cafes, bars, and shops. Lively by day, electric by night.' },
      { img: 'web-yulong-karst', title: 'Yangshuo Karst Countryside', sub: '阳朔田园 · Peaks & paddies', text: 'The town is ringed by cone-shaped limestone towers, rice fields, and villages — the landscape that makes Yangshuo unforgettable.' },
      { img: 'exp-cycling', title: 'Countryside Cycling', sub: '骑行 · Flat trails', text: 'Rent a bike (¥20–30/day) and loop through villages, rice paddies, and Moon Hill. Safe, flat, and gorgeous.' },
      { img: 'exp-climb', title: 'Karst Rock Climbing', sub: '攀岩 · World-class', text: 'Yangshuo is Asia’s top sport-climbing destination, with routes for every level on the surrounding towers.' },
      { img: 'attraction-xingping', title: 'Xingping Ancient Town', sub: '兴坪 · 30 min away', text: 'A 1,700-year-old town on the Li River, directly opposite the famous ¥20 banknote karst view.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Arrive by Cruise', meta: '4–5 hours · From Guilin · ends in Yangshuo',
        steps: [
          { t: 'Cruise the Li River', d: 'Disembark at Yangshuo pier in the early afternoon.' },
          { t: 'Drop bags at your hotel', d: 'Dozens within walking distance of West Street.' },
          { t: 'Walk West Street at dusk', d: 'Cafes, bars, and street food come alive after dark.' },
        ],
      },
      {
        icon: 'anchor', title: 'Countryside Loop (Bike)', meta: 'Half day · ~20 km · flat',
        steps: [
          { t: 'Rent a bike', d: '¥20–30/day from any shop near West Street.' },
          { t: 'Ride to Yulong River', d: 'Follow the riverside path past paddies and karst towers.' },
          { t: 'Climb Moon Hill', d: 'A short, steep stair climb for a panoramic valley view.' },
          { t: 'Return via Gaotian', d: 'Loop back through villages to town before dark.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'Apr – May', text: 'Green rice fields, misty peaks, comfortable biking weather.' },
      { icon: 'calendar-heart', title: 'Sep – Nov', text: 'Golden harvest, clear skies, the most popular season to stay overnight.' },
      { icon: 'sun', title: 'Year-round nights', text: 'West Street and the riverside show run every evening, rain or shine.' },
    ],
    tips: [
      { icon: 'clock', title: 'Spend the night', text: 'Day-trippers miss the best part. The countryside at sunrise and West Street at night are the highlights.' },
      { icon: 'camera', title: 'Shoot Moon Hill at sunrise', text: 'Bike out before 8 AM for empty roads and soft light on the karst.' },
      { icon: 'sun', title: 'Bring a bike light', text: 'Country roads have no streetlights; rent a bike with a working light if you’ll be out late.' },
      { icon: 'utensils', title: 'Eat Beer Fish', text: 'Yangshuo’s signature dish — fresh river fish braised in beer. Try it on West Street.' },
      { icon: 'droplet', title: 'Book the night show early', text: 'Impression Liu Sanjie sells out in peak season; your hotel can secure seats.' },
    ],
    gettingThere: [
      { t: 'By Li River cruise', d: 'The classic 4–5 hour cruise from Guilin ends at Yangshuo pier.' },
      { t: 'By bus from Guilin', d: 'Frequent express buses (about 70–90 min, ¥25–30) from Guilin bus station.' },
      { t: 'By high-speed rail', d: 'Guilin–Yangshuo trains run several times a day (about 30–40 min); the station is 30 min from town.' },
      { t: 'By car', d: 'Private transfer about 70 min; your hotel can arrange pickup.' },
    ],
    tickets: [
      ['Impression Liu Sanjie show', '¥320–680 — book ahead in peak season'],
      ['Bike rental', '¥20–30/day'],
      ['Yulong bamboo raft', '¥120–255 (see Yulong River page)'],
      ['Moon Hill entrance', '¥35–45'],
      ['From Guilin (bus)', '¥25–30 · 70–90 min'],
      ['High-speed rail', '¥25–40 · 30–40 min'],
    ],
    ticketNote: 'Yangshuo town itself is free to wander. Paid items are the show, rafting, and individual viewpoints. The night show price varies hugely by seat section — book through your hotel for the best rate.',
    gallery: [
      { img: 'attraction-yangshuo', alt: 'Yangshuo West Street at night' },
      { img: 'web-yulong-karst', alt: 'Yangshuo karst countryside' },
      { img: 'exp-cycling', alt: 'Countryside cycling near Yangshuo' },
      { img: 'exp-climb', alt: 'Karst rock climbing near Yangshuo' },
      { img: 'attraction-yulong', alt: 'Yulong River scenery near Yangshuo' },
      { img: 'attraction-xingping', alt: 'Xingping ancient town near Yangshuo' },
    ],
    faqs: [
      { q: 'Should I stay in Yangshuo or just visit for the day?', a: 'Stay at least one night. The countryside at sunrise and West Street at night are the best parts, and the Li River cruise already delivers you here in the afternoon — it would be a shame to leave the same day.' },
      { q: 'Is Yangshuo walkable and foreigner-friendly?', a: 'Very. The town center is compact and flat, most hotels and tour desks speak English, and West Street is full of English menus and international travelers.' },
      { q: 'What’s the Impression Liu Sanjie show?', a: 'A huge open-air performance directed by Zhang Yimou on a natural stretch of the Li River, using hundreds of local performers, lights, and mist. It sells out in peak season, so book ahead through your hotel.' },
      { q: 'Can I bike the countryside easily?', a: 'Yes — it’s flat, safe, and signposted in places. Rent a bike for ¥20–30/day and loop to the Yulong River and Moon Hill. Roads are unlit at night, so return before dark or take a light.' },
      { q: 'How do I get from Guilin to Yangshuo?', a: 'Three easy ways: the Li River cruise (scenic, 4–5 h), an express bus (¥25–30, 70–90 min), or high-speed rail (¥25–40, 30–40 min). The station is 30 minutes from town by car.' },
      { q: 'Is rock climbing beginner-friendly here?', a: 'Yes. Yangshuo is Asia’s top sport-climbing destination with routes from absolute beginner to expert, and many English-speaking guide outfits in town.' },
    ],
    quickFacts: [
      ['From Guilin', '65 km · 70–90 min'],
      ['Stay', '1–2 nights'],
      ['Best season', 'Apr–May · Sep–Nov'],
      ['Signature', 'West Street (西街)'],
      ['Bike rental', '¥20–30/day'],
      ['Night show', '¥320–680'],
      ['Famous for', 'Karst countryside'],
    ],
    localTip: 'Skip the touts near the pier offering “private” trips. Walk 10 minutes into town, and every second shop rents honest bikes and sells raft tickets at the standard rate.',
    related: [
      { slug: 'liriver', img: 'hero-liriver', title: 'Li River Cruise', sub: '漓江 · Arrives in Yangshuo' },
      { slug: 'yulong', img: 'attraction-yulong', title: 'Yulong River Rafting', sub: '遇龙河 · Just outside town' },
      { slug: 'xingping', img: 'attraction-xingping', title: 'Xingping Ancient Town', sub: '兴坪 · 20-yuan view' },
      { slug: 'elephant', img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · In Guilin city' },
    ],
    geo: { lat: 24.778, lng: 110.498 },
  },

  /* ============================ 4. LONGJI RICE TERRACES ============================ */
  {
    slug: 'longji',
    name: 'Longji Rice Terraces',
    cnName: '龙脊',
    kicker: "Dragon-Back Terraces · ~100 km from Guilin",
    heroImage: 'attraction-longji',
    ogImage: 'attraction-longji',
    tagline: '龙脊 · Stairways to the Sky',
    lead: 'A 650-year-old masterpiece carved into the mountains — ribbons of rice terraces spiraling up slopes above 1,000 meters. In May–June they mirror the sky with water; in September–October they turn to liquid gold.',
    glance: '<strong class="text-river">Longji Rice Terraces (龙脊)</strong> — “Dragon’s Backbone” — are a network of terraced fields built by Zhuang and Yao minorities over 650 years, about 100&nbsp;km (2.5–3 hours) from Guilin. The highest fields sit above 1,100&nbsp;m. Two main areas draw visitors: <strong class="text-river">Ping’an (Zhuang)</strong> for the classic postcard curves, and <strong class="text-river">Jinkeng Red Yao</strong> for vast terraces and sunrise sea-of-clouds.',
    intro: [
      'Imagine a mountainside combed into ribbons of water and rice, climbing so high they seem to touch the clouds. That’s Longji. Local Zhuang and Yao farmers began carving these terraces in the Yuan dynasty and finished them over centuries — an engineering feat done entirely by hand, still farmed the same way today.',
      'There are two headline areas. <strong class="text-river">Ping’an Village (平安寨)</strong> has the iconic “Seven Stars with the Moon” and “Nine Dragons and Five Tigers” viewpoints — the curves you’ve seen on every China calendar. <strong class="text-river">Jinkeng Dazhai (金坑大寨)</strong>, home to the Red Yao people, is bigger and higher, famous for sunrise “sea of clouds” and a cable car if you’d rather not hike.',
      '<span class="text-sm text-stone-600"><em>Quick tip: the terraces look completely different by season. Go in May–June for mirror-like flooded fields, or late September–October for the golden harvest. Avoid mid-summer (hot, muddy) and deep winter (cold, sometimes frost).</em></span>',
    ],
    highlights: [
      { img: 'attraction-longji', title: 'The Terraces Themselves', sub: '龙脊梯田 · Hand-carved', text: 'Ribbons of field climbing the mountainside — a 650-year-old landscape still farmed by Zhuang and Yao families.' },
      { img: 'exp-longji', title: 'Longji Terraced Fields', sub: '梯田四季 · Year-round', text: 'The same layered hillsides in a different season: flooded silver in spring, lush green in summer, or gold in autumn.' },
      { img: 'web-longji-jinkeng', title: 'Jinkeng Dazhai Terraces', sub: '金坑大寨 · Sea of clouds', text: 'The higher Jinkeng area offers vast terraces and famous sunrise sea-of-clouds views above Red Yao villages.' },
      { img: 'attraction-yangshuo', title: 'Yangshuo Countryside', sub: '阳朔田园 · Combine with Longji', text: 'Many travelers pair the terraces with Yangshuo’s karst peaks in the same trip.' },
      { img: 'attraction-reedflute', title: 'Reed Flute Cave', sub: '芦笛岩 · On the way back', text: 'A cool Guilin cave visit fits neatly on the return drive from Longji.' },
    ],
    routes: [
      {
        icon: 'anchor', title: 'Ping’an (Classic)', meta: 'Half–full day · 2.5 h from Guilin',
        steps: [
          { t: 'Drive from Guilin', d: 'Private car or tour bus, about 2.5–3 hours.' },
          { t: 'Hike to Seven Stars viewpoint', d: 'A 30–45 min paved climb with the famous curved terraces.' },
          { t: 'Walk to Nine Dragons', d: 'A second viewpoint 20 min away; flat between them.' },
          { t: 'Return via the village', d: 'Browse Yao handicrafts and try a farm lunch.' },
        ],
      },
      {
        icon: 'ship', title: 'Jinkeng Dazhai (Big & High)', meta: 'Full day · cable car option',
        steps: [
          { t: 'Ride the cable car', d: 'Or hike 1.5–2 h up to the Golden Buddha Peak viewpoint.' },
          { t: 'Watch the sunrise', d: 'Stay in a guesthouse to catch the sea of clouds at dawn.' },
          { t: 'Explore Red Yao hamlets', d: 'Lower slopes have traditional wooden stilt houses.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'May – Jun', text: 'Flooded terraces mirror the sky — silvery, calm, fewer crowds than autumn.' },
      { icon: 'calendar-heart', title: 'Late Sep – Oct', text: 'Golden harvest — the postcard view, but the busiest and priciest time.' },
      { icon: 'cloud-rain', title: 'Avoid Jul–Aug', text: 'Hot, humid, and muddy underfoot; winter is cold but peaceful if you don’t mind frost.' },
    ],
    tips: [
      { icon: 'clock', title: 'Start before 6 AM for sunrise', text: 'The famous sea-of-clouds shots need you at the viewpoint before dawn. Stay in a village guesthouse.' },
      { icon: 'sun', title: 'Pack layers', text: 'At 1,000+ m it’s 5–10°C cooler than Guilin, and mornings are cold even in spring.' },
      { icon: 'camera', title: 'Bring a zoom lens', text: 'The terrace curves and distant peaks reward a telephoto; drones are restricted near villages.' },
      { icon: 'utensils', title: 'Eat a farm lunch', text: 'Village guesthouses serve simple, delicious Zhuang/Yao home cooking — bamboo rice, free-range chicken.' },
      { icon: 'droplet', title: 'Wear grippy shoes', text: 'Stone paths are steep and slick after rain. Skip sandals.' },
    ],
    gettingThere: [
      { t: 'By tour / private car', d: 'Easiest for foreign visitors: about 2.5–3 h from Guilin, door to viewpoint.' },
      { t: 'By long-distance bus', d: 'Guilin bus station has direct buses to Longsheng (¥50–60, ~3 h), then a local shuttle up to the terraces.' },
      { t: 'Stay overnight', d: 'Guesthouses in Ping’an or Jinkeng put sunrise viewpoints within walking distance.' },
      { t: 'Cable car at Jinkeng', d: 'Saves the climb if you’d rather not hike; runs during daylight hours.' },
    ],
    tickets: [
      ['Entrance ticket', '¥80–95 — covers the terrace areas'],
      ['Jinkeng cable car', '¥55–100 one way (optional)'],
      ['From Guilin', '2.5–3 hours by car'],
      ['Best months', 'May–Jun · Late Sep–Oct'],
      ['Elevation', 'up to ~1,100 m'],
      ['Suggested stay', '1 night for sunrise'],
    ],
    ticketNote: 'One ticket covers the terrace scenic areas. The cable car at Jinkeng is separate. Prices rise during the October golden-rice peak. Book village guesthouses ahead in harvest season.',
    gallery: [
      { img: 'attraction-longji', alt: 'Longji rice terraces' },
      { img: 'exp-longji', alt: 'Longji terraced fields' },
      { img: 'web-longji-jinkeng', alt: 'Jinkeng rice terraces at Longji' },
      { img: 'attraction-yangshuo', alt: 'Yangshuo West Street — a common stop with Longji' },
      { img: 'attraction-reedflute', alt: 'Reed Flute Cave — near Guilin, on the way back from Longji' },
      { img: 'attraction-elephant', alt: 'Elephant Trunk Hill — Guilin city symbol, easy stop after Longji' },
    ],
    faqs: [
      { q: 'When is the best time to see the terraces?', a: 'Two windows: May–June, when the fields are flooded and mirror the sky (quiet, silvery), and late September–October, when the rice turns gold (the classic postcard, but busy and pricier). Avoid midsummer heat and deep winter cold.' },
      { q: 'Ping’an or Jinkeng — which should I choose?', a: 'Ping’an has the iconic curved terraces and is more compact; Jinkeng is larger, higher, and has the cable car plus the best sea-of-clouds sunrises. Many tours do both. First-timers often prefer Ping’an for the famous viewpoints.' },
      { q: 'Do I need to hike a lot?', a: 'The main viewpoints are 30–45 min paved climbs from the village. At Jinkeng you can take a cable car instead. Paths are steep and slick after rain, so wear grippy shoes.' },
      { q: 'Can I stay overnight?', a: 'Yes, and you should if you want sunrise. Wooden guesthouses in both Ping’an and Jinkeng put the viewpoints within walking distance and serve hearty local food.' },
      { q: 'How far is Longji from Guilin?', a: 'About 100 km, roughly 2.5–3 hours by car or tour bus. A private car or guided day trip is the easiest option for foreign visitors.' },
      { q: 'What’s the Red Yao culture about?', a: 'The Red Yao are one of the ethnic groups who built and farm the terraces. Their women are known for extraordinarily long hair and red embroidery; visiting a village adds a cultural layer beyond the views.' },
    ],
    quickFacts: [
      ['From Guilin', '~100 km · 2.5–3 h'],
      ['Elevation', 'up to ~1,100 m'],
      ['Age', '650+ years'],
      ['Best season', 'May–Jun · Sep–Oct'],
      ['Ticket', '¥80–95'],
      ['Stay', '1 night for sunrise'],
      ['Famous for', 'Dragon-back terraces'],
    ],
    localTip: 'Most day-trippers arrive at 10 AM and leave by 3 PM. If you stay overnight, you’ll have the sunrise viewpoints — and the best light — almost to yourself.',
    related: [
      { slug: 'liriver', img: 'hero-liriver', title: 'Li River Cruise', sub: '漓江 · Pair with a 3-day trip' },
      { slug: 'yangshuo', img: 'attraction-yangshuo', title: 'Yangshuo & West Street', sub: '阳朔 · Countryside cousin' },
      { slug: 'reedflute', img: 'attraction-reedflute', title: 'Reed Flute Cave', sub: '芦笛岩 · On the way back' },
      { slug: 'elephant', img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · Guilin city' },
    ],
    geo: { lat: 25.78, lng: 110.13 },
  },

  /* ============================ 5. REED FLUTE CAVE ============================ */
  {
    slug: 'reedflute',
    name: 'Reed Flute Cave',
    cnName: '芦笛岩',
    kicker: "Nature's Underground Palace · 5 km NW of Guilin",
    heroImage: 'attraction-reedflute',
    ogImage: 'attraction-reedflute',
    tagline: '芦笛岩 · The Palace of Natural Arts',
    lead: 'A 180-million-year-old limestone cave lit like a fairy tale — stalactites, stalagmites, and an underground lake mirror-polished by colored light. A cool, easy 1-hour walk, perfect when the weather outside isn’t cooperating.',
    glance: '<strong class="text-river">Reed Flute Cave (芦笛岩)</strong> is a 180-million-year-old limestone cavern about 5&nbsp;km northwest of Guilin city. Its name comes from the reeds growing outside that locals once made into flutes. Inside, a 500-meter walkway winds past illuminated stalactites, stone pillars, and a mirror-still underground lake. Tang-dynasty visitors carved poems on the walls over 1,200 years ago.',
    intro: [
      'Step from the Guilin heat or rain into a constant 19°C wonderland. Reed Flute Cave has been a tourist draw for over 1,200 years — you can still see poems carved into the rock by Tang dynasty visitors in 792 AD. What makes it special today is the lighting: stalactites and pillars glow in shifting colors, and a calm underground lake doubles the whole scene like a mirror.',
      'The walkable route is about <strong class="text-river">500 meters</strong> of flat, well-lit path — no crawling, no climbing, no getting dirty. Guides love to point out shapes: a “Crystal Palace,” a “Dragon Tower,” a “Virgin Forest.” It’s theatrical, yes, but genuinely spectacular and a relief on a hot or wet summer day.',
      '<span class="text-sm text-stone-600"><em>Quick tip: it’s cool and damp inside year-round (about 19°C). Bring a light layer in summer, and go early to beat the tour-bus crowds that arrive late morning.</em></span>',
    ],
    highlights: [
      { img: 'attraction-reedflute', title: 'The Crystal Palace', sub: '水晶宫 · The showpiece', text: 'A vast chamber with a stage-like rock floor and a ceiling of hanging stalactites — the cave’s theatrical centerpiece.' },
      { img: 'web-reedflute-3', title: 'Stalactite Forest', sub: '石笋森林 · Lit formations', text: 'Colorful lights pick out stone pillars and hanging formations inside the cave.' },
      { img: 'web-reedflute-4', title: 'Underground Mirror Lake', sub: '地下湖 · Reflections', text: 'A still underground lake doubles the lit stalactites in a perfect mirror.' },
      { img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · 20 min away', text: 'Guilin’s city emblem sits where the Li and Peach Blossom rivers meet — easy to pair with the cave in one morning.' },
      { img: 'web-tworivers-bridge', title: 'Sun & Moon Pagodas', sub: '日月双塔 · City center lakes', text: 'A gold and a silver pagoda light up on Shanhu Lake at night — the signature sight on an evening lakeside walk.' },
    ],
    routes: [
      {
        icon: 'anchor', title: 'Standard Cave Walk', meta: '1 hour · 500 m · flat',
        steps: [
          { t: 'Enter the north mouth', d: 'Buy a ticket; the path descends gently into the cavern.' },
          { t: 'Follow the lit loop', d: 'Past the Crystal Palace, lake, and named formations.' },
          { t: 'Exit the south mouth', d: 'A short walk back to the parking area and shuttle.' },
        ],
      },
      {
        icon: 'ship', title: 'Cave + City Combo', meta: 'Half day · with Guilin sights',
        steps: [
          { t: 'Morning cave visit', d: 'Cool and quiet before the tour buses (arrive ~9 AM).' },
          { t: 'Afternoon in the city', d: 'Pair with Elephant Trunk Hill and the lakes, 20 min away.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'sun', title: 'Hot summer days', text: 'A constant 19°C inside makes it the perfect air-conditioned escape in Jul–Aug.' },
      { icon: 'cloud-rain', title: 'Rainy days', text: 'Fully indoor — ideal when the Li River cruise or biking is washed out.' },
      { icon: 'calendar-heart', title: 'Year-round', text: 'The cave is weatherproof; only the crowds vary by season.' },
    ],
    tips: [
      { icon: 'clock', title: 'Arrive before 10 AM', text: 'Tour buses flood in late morning; early means empty chambers and clean photos.' },
      { icon: 'sun', title: 'Bring a light layer', text: 'It’s ~19°C and damp inside even in August — a thin jacket is welcome.' },
      { icon: 'camera', title: 'Use the lake for reflections', text: 'The underground lake is the mirror shot; crouch low and turn off flash for the best result.' },
      { icon: 'utensils', title: 'Snacks at the exit', text: 'A small plaza outside sells drinks and souvenirs; nothing inside.' },
      { icon: 'droplet', title: 'Watch the floor', text: 'Paths are damp in spots — sensible shoes, no heels.' },
    ],
    gettingThere: [
      { t: 'From Guilin city', d: 'About 5 km northwest; taxi 15–20 min (¥20–30).' },
      { t: 'By bus', d: 'City bus 3 or tourist shuttles stop near the entrance.' },
      { t: 'With a tour', d: 'Most Guilin day tours include the cave as a stop.' },
      { t: 'Tickets', d: 'Buy at the gate or via your hotel; no advance booking required.' },
    ],
    tickets: [
      ['Entrance ticket', '¥85–110 — includes the lit walkway'],
      ['Visit time', '~1 hour'],
      ['Walkway', '~500 m · flat'],
      ['Temperature', '~19°C year-round'],
      ['From Guilin', '5 km · 15–20 min'],
      ['Inside', 'No climbing or crawling'],
    ],
    ticketNote: 'Prices are reference values and may shift by season. The cave is fully accessible and stroller/wheelchair friendly on the main path. Photography is allowed without flash.',
    gallery: [
      { img: 'attraction-reedflute', alt: 'Reed Flute Cave formations' },
      { img: 'web-reedflute-2', alt: 'Reed Flute Cave interior' },
      { img: 'web-reedflute-3', alt: 'Reed Flute Cave stalactites' },
      { img: 'web-reedflute-4', alt: 'Reed Flute Cave underground lake' },
      { img: 'attraction-elephant', alt: 'Elephant Trunk Hill near Reed Flute Cave' },
      { img: 'web-tworivers-bridge', alt: 'Sun and Moon Pagodas near Reed Flute Cave' },
    ],
    faqs: [
      { q: 'How long does a visit take?', a: 'About one hour for the 500-meter lit walkway. Add time for photos and the souvenir plaza outside. It’s an easy, flat, fully indoor visit.' },
      { q: 'Is it suitable for kids, strollers, and wheelchairs?', a: 'Yes — the main path is flat, well-lit, and paved, with no climbing or crawling. Strollers and wheelchairs manage it fine.' },
      { q: 'Why is it called Reed Flute Cave?', a: 'Reeds growing at the cave entrance were traditionally used to make flutes. The name is poetic, not because flutes are found inside.' },
      { q: 'Is it cold inside?', a: 'It stays around 19°C (66°F) all year. Bring a light layer in summer, and it’s a cozy escape in winter.' },
      { q: 'When should I go to avoid crowds?', a: 'Arrive right at opening (~9 AM). Tour buses arrive late morning and the chambers get busy. Early also gives the clearest photos.' },
      { q: 'How do I combine it with other sights?', a: 'It’s 15–20 minutes from Guilin city center — pair with Elephant Trunk Hill and the Two Rivers & Four Lakes lakes in one half-day.' },
    ],
    quickFacts: [
      ['Age', '180 million years'],
      ['Visit time', '~1 hour'],
      ['Walkway', '~500 m · flat'],
      ['Temperature', '~19°C'],
      ['Ticket', '¥85–110'],
      ['From Guilin', '5 km'],
      ['Famous for', 'Lit limestone palace'],
    ],
    localTip: 'Skip the on-site photo print stands — they’re overpriced. Your phone on the underground lake (no flash) will beat them anyway.',
    related: [
      { slug: 'elephant', img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · 20 min away' },
      { slug: 'tworivers', img: 'attraction-tworivers', title: 'Two Rivers & Four Lakes', sub: '两江四湖 · Evening cruise' },
      { slug: 'liriver', img: 'hero-liriver', title: 'Li River Cruise', sub: '漓江 · The big day' },
      { slug: 'longji', img: 'attraction-longji', title: 'Longji Rice Terraces', sub: '龙脊 · Longer trip' },
    ],
    geo: { lat: 25.30, lng: 110.27 },
  },

  /* ============================ 6. YULONG RIVER ============================ */
  {
    slug: 'yulong',
    name: 'Yulong River Rafting',
    cnName: '遇龙河',
    kicker: "The Little Li River · Just outside Yangshuo",
    heroImage: 'attraction-yulong',
    ogImage: 'attraction-yulong',
    tagline: '遇龙河 · Quieter than the Cruise, Closer to the Water',
    lead: 'A tranquil tributary of the Li River where you drift on a shallow bamboo raft between intimate karst peaks, old stone bridges, and rice paddies. No big cruise boats, no crowds — just you, the water, and the hills.',
    glance: '<strong class="text-river">The Yulong River (遇龙河)</strong> is a gentle tributary of the Li River, flowing through the countryside just south of Yangshuo. Its bamboo-raft trips are the peaceful alternative to the big Guilin–Yangshuo cruise: smaller rafts, lower water, and a more personal karst landscape. The most scenic stretch runs from <strong class="text-river">Jima to Gongnong Bridge</strong>.',
    intro: [
      'If the Li River cruise is the headline, the Yulong is the deep cut. The water here is shallower and the peaks lower and rounder, so you float close to the surface, almost at eye level with the karst. There are no engine-roar cruise ships — just hand-poled or small-motor bamboo rafts, old arched stone bridges, and the occasional water buffalo.',
      'The classic rafting section runs from <strong class="text-river">Jima (骥马)</strong> downstream to <strong class="text-river">Gongnong Bridge (工农桥)</strong>, about 1–1.5 hours of pure calm. Some stretches pass working villages where you can hop off, rent a bike, and continue along the riverside path.',
      '<span class="text-sm text-stone-600"><em>Quick tip: the Yulong is best in the morning, when mist hangs over the water and the light is soft. Combine a raft with a bike loop — many travelers raft down, then ride back through the fields.</em></span>',
    ],
    highlights: [
      { img: 'attraction-yulong', title: 'The Bamboo Raft', sub: '竹筏 · Close to water', text: 'Shallow bamboo rafts drift just above the surface — you’re almost level with the river, not looking down from a cruise deck.' },
      { img: 'exp-bamboo', title: 'Bamboo Rafting', sub: '竹筏漂流 · Quiet stretch', text: 'A raft carrying two visitors poles along a green river lined with bamboo and karst peaks — the Yulong experience in one frame.' },
      { img: 'attraction-yangshuo', title: 'West Street at Night', sub: '西街 · Yangshuo base', text: 'Yangshuo’s 1,400-year-old pedestrian street is where most travelers stay, eat, and book their Yulong raft trip.' },
      { img: 'exp-cycling', title: 'Riverside Bike Loop', sub: '骑行 · Combine', text: 'Raft down, then bike back through paddies and hamlets on flat paths. The perfect Yangshuo morning.' },
      { img: 'attraction-xingping', title: 'Xingping Ancient Town', sub: '兴坪 · Nearby', text: 'The historic Li River town is an easy stop when basing yourself in Yangshuo for the Yulong.' },
    ],
    routes: [
      {
        icon: 'anchor', title: 'Classic Raft (Jima → Gongnong)', meta: '1–1.5 hours · ¥200–300',
        steps: [
          { t: 'Reach Jima pier', d: 'A 15-min drive or bike from Yangshuo West Street.' },
          { t: 'Board the bamboo raft', d: '2 people per raft; life jackets provided, shallow and stable.' },
          { t: 'Drift to Gongnong Bridge', d: 'Past bridges, buffaloes, and karst bends.' },
          { t: 'Bike or taxi back', d: 'Rent a bike at the exit and ride the riverside path home.' },
        ],
      },
      {
        icon: 'ship', title: 'Raft + Bike Combo', meta: 'Half day · best of both',
        steps: [
          { t: 'Morning raft', d: 'Cool, misty, and quiet before the crowds.' },
          { t: 'Bike the return', d: 'Flat riverside trail through villages and paddies.' },
          { t: 'Lunch in a hamlet', d: 'Simple farm restaurants line the path.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'Apr – May', text: 'Green banks, full river, light mist — the most romantic season.' },
      { icon: 'calendar-heart', title: 'Sep – Nov', text: 'Clear, comfortable, golden fields lining the banks.' },
      { icon: 'sun', title: 'Mornings year-round', text: 'Go at first light for mist and soft photos; afternoons get busy.' },
    ],
    tips: [
      { icon: 'clock', title: 'Raft before 9 AM', text: 'Mist, soft light, and empty rafts. Later the river fills with other tours.' },
      { icon: 'sun', title: 'Bring sun protection', text: 'Open rafts have no shade. Hat, sunscreen, and water are essential.' },
      { icon: 'camera', title: 'Shoot the bridges', text: 'Frame the old arched bridges with peaks behind — the iconic Yulong composition.' },
      { icon: 'utensils', title: 'Pack a snack', text: 'Few facilities on the water; eat before or after in a village.' },
      { icon: 'droplet', title: 'Check water level', text: 'After heavy rain the river may be too high for rafts; ask locally the day before.' },
    ],
    gettingThere: [
      { t: 'From Yangshuo', d: 'Jima pier is a 15-min drive or bike ride from West Street.' },
      { t: 'By bike', d: 'Flat riverside paths connect Yangshuo to the raft piers — ride there, raft back.' },
      { t: 'Tickets', d: 'Buy at the pier or via your hotel; two people share a raft.' },
      { t: 'Combine', d: 'Easy to pair with Moon Hill and the countryside in one morning.' },
    ],
    tickets: [
      ['Bamboo raft (Jima–Gongnong)', '¥200–300 per raft (2 people)'],
      ['Duration', '1–1.5 hours'],
      ['From Yangshuo', '15 min by bike/car'],
      ['Best months', 'April–May · Sep–Nov'],
      ['Best time', 'Morning, for mist'],
      ['Difficulty', 'Easy · sit back'],
    ],
    ticketNote: 'Rafts seat two and run on a set section; prices are reference values and rise in peak season. Rafts pause during heavy rain or high water for safety. Bring your passport — it may be checked.',
    gallery: [
      { img: 'attraction-yulong', alt: 'Yulong River bamboo raft' },
      { img: 'exp-bamboo', alt: 'Bamboo raft on the Yulong River' },
      { img: 'attraction-yangshuo', alt: 'Yangshuo West Street — base for Yulong trips' },
      { img: 'exp-cycling', alt: 'Riverside bike loop near the Yulong River' },
      { img: 'attraction-xingping', alt: 'Xingping ancient town near the Yulong River' },
    ],
    faqs: [
      { q: 'How is the Yulong different from the Li River cruise?', a: 'The Yulong is a smaller, shallower tributary with bamboo rafts instead of big cruise boats. You sit low on the water near the karst, it’s quieter and more intimate, and it’s much cheaper — but shorter (1–1.5 h vs 4–5 h).' },
      { q: 'Which raft section is best?', a: 'Jima to Gongnong Bridge is the classic, most scenic 1–1.5 hour stretch, with arched stone bridges and open karst. It’s the one most travelers and photos reference.' },
      { q: 'Can I combine rafting with biking?', a: 'Easily — raft downstream, then bike back along flat riverside paths through villages and paddies. It’s the perfect Yangshuo morning and very safe.' },
      { q: 'Is it safe for non-swimmers and kids?', a: 'Yes — rafts are stable, shallow, and life jackets are provided. Children are welcome; just keep them seated.' },
      { q: 'When should I go?', a: 'First thing in the morning for mist, soft light, and few people. Afternoons get busy and the sun is strong with no shade on the raft.' },
      { q: 'How do I get there from Yangshuo?', a: 'Jima pier is about 15 minutes by bike or car from West Street. You can also bike the whole way on flat paths and raft back.' },
    ],
    quickFacts: [
      ['Type', 'Tributary of Li River'],
      ['Raft time', '1–1.5 hours'],
      ['Best section', 'Jima → Gongnong'],
      ['Best season', 'Apr–May · Sep–Nov'],
      ['Ticket', '¥200–300/raft'],
      ['From Yangshuo', '15 min'],
      ['Famous for', 'Quiet bamboo rafting'],
    ],
    localTip: 'Don’t book the longest raft section just because it’s “more.” The Jima–Gongnong stretch has all the best bridges and bends in the shortest, calmest ride.',
    related: [
      { slug: 'yangshuo', img: 'attraction-yangshuo', title: 'Yangshuo & West Street', sub: '阳朔 · Your base' },
      { slug: 'liriver', img: 'hero-liriver', title: 'Li River Cruise', sub: '漓江 · The bigger sister' },
      { slug: 'xingping', img: 'attraction-xingping', title: 'Xingping Ancient Town', sub: '兴坪 · Nearby' },
      { slug: 'elephant', img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · Guilin city' },
    ],
    geo: { lat: 24.83, lng: 110.45 },
  },

  /* ============================ 7. TWO RIVERS & FOUR LAKES ============================ */
  {
    slug: 'tworivers',
    name: 'Two Rivers & Four Lakes',
    cnName: '两江四湖',
    kicker: "Guilin's Water Ring · City Center",
    heroImage: 'attraction-tworivers',
    ogImage: 'attraction-tworivers',
    tagline: '两江四湖 · The City That Floats',
    lead: 'Guilin’s downtown is wrapped in water — two rivers and four connected lakes you can walk by day and cruise by night, when the Sun and Moon Pagodas light up like lanterns on the water.',
    glance: '<strong class="text-river">Two Rivers & Four Lakes (两江四湖)</strong> is Guilin’s central water system: the <strong class="text-river">Li River</strong> and <strong class="text-river">Peach Blossom River</strong> (the two rivers), plus <strong class="text-river">Shanhu, Ronghu, Guihu, and Mulong Lake</strong> (the four lakes), linked into one ring around the old city. By day it’s a shady promenade; by night, an illuminated cruise past bridges and pagodas.',
    intro: [
      'Guilin’s genius is that its city center is built around water. The Li River and Peach Blossom River run through town, and four lakes — Shan, Rong, Gui, and Mulong — are connected into a loop you can walk or boat. Locals jog and dance along the lakeside paths every evening; visitors come for the <strong class="text-river">night cruise</strong>.',
      'The headline sight is on <strong class="text-river">Shanhu Lake (杉湖)</strong>: the <strong class="text-river">Sun and Moon Pagodas (日月双塔)</strong>, a pair of towers — one gold, one silver — that glow on the water after dark. Nearby, Ronghu’s ancient city wall and Mulong Lake’s replica of a Song-dynasty water gate add history to the stroll.',
      '<span class="text-sm text-stone-600"><em>Quick tip: the walk is free and lovely any time, but do the boat at night at least once — the lit bridges and the twin pagodas reflected in the water are the signature Guilin evening.</em></span>',
    ],
    highlights: [
      { img: 'attraction-tworivers', title: 'Sun & Moon Pagodas', sub: '日月双塔 · On Shanhu Lake', text: 'A gold and a silver pagoda that light up on the water at night — Guilin’s most photographed evening sight.' },
      { img: 'web-tworivers-nightcruise', title: 'Night Cruise View', sub: '夜游两江四湖 · Illuminated ring', text: 'A night boat passes the twin pagodas, lit bridges, and the city’s water-ring glow.' },
      { img: 'web-tworivers-bridge', title: 'Pagodas by Night', sub: '双塔倒影 · Reflections', text: 'The gold-and-silver towers reflected on Shanhu Lake after dark.' },
      { img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · 10-min walk', text: 'Guilin’s city emblem sits where the Li and Peach Blossom rivers meet — an easy addition to a lakeside evening.' },
      { img: 'web-elephant-night', title: 'Elephant Hill Night Lights', sub: '象鼻山夜景 · Golden silhouette', text: 'Nearby Elephant Trunk Hill glows gold after dark — easy to combine with a lakes cruise.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Night Cruise (Classic)', meta: '1–2 hours · ¥210–320',
        steps: [
          { t: 'Board near Shanhu', d: 'Piers on the central lakes; your hotel can book.' },
          { t: 'Cruise the ring', d: 'Past the twin pagodas, lit bridges, and the Li River stretch.' },
          { t: 'Disembark lakeside', d: 'Step straight onto the promenade for a late stroll.' },
        ],
      },
      {
        icon: 'anchor', title: 'Self-Guided Walk', meta: 'Free · 1–2 hours · flat',
        steps: [
          { t: 'Start at Elephant Trunk Hill', d: 'Walk north along the riverside promenade.' },
          { t: 'Loop the four lakes', d: 'Shan → Rong → Gui → Mulong, all connected.' },
          { t: 'End at the twin pagodas', d: 'Time it for dusk to watch them light up.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'sun', title: 'Dusk → night', text: 'The pagodas and bridges switch on around sunset — the reason to come.' },
      { icon: 'calendar-heart', title: 'Spring & autumn', text: 'Comfortable for the open promenade walk.' },
      { icon: 'cloud-rain', title: 'Avoid heavy rain', text: 'The boat may pause; the walk is still fine under light drizzle.' },
    ],
    tips: [
      { icon: 'clock', title: 'Cruise at dusk', text: 'Boats leaving around sunset catch both daylight and the full light show.' },
      { icon: 'camera', title: 'Shoot the twin pagodas', text: 'From the Shanhu lakeside with the reflection — best 20–30 min after lights on.' },
      { icon: 'sun', title: 'Walk is free', text: 'You don’t need a ticket to enjoy the lakes; only the boat costs.' },
      { icon: 'utensils', title: 'Dinner along the lake', text: 'Ronghu’s western bank has lakeside restaurants — eat with the view.' },
      { icon: 'droplet', title: 'Boat sells out', text: 'Night cruises fill in peak season; book through your hotel.' },
    ],
    gettingThere: [
      { t: 'From Guilin city center', d: 'The lakes are in the heart of town — walkable from most hotels.' },
      { t: 'From Elephant Trunk Hill', d: 'A 10-minute riverside walk north reaches Shanhu Lake.' },
      { t: 'Cruise piers', d: 'On the central lakes; your hotel or any tour desk sells tickets.' },
      { t: 'Tickets', d: 'Walk free; boat tickets ¥210–320, book ahead in season.' },
    ],
    tickets: [
      ['Night cruise', '¥210–320 · 1–2 hours'],
      ['Lakeside walk', 'Free'],
      ['Best time', 'Dusk → night'],
      ['Location', 'Guilin city center'],
      ['From Elephant Hill', '10-min walk'],
      ['Boat books out', 'Peak season'],
    ],
    ticketNote: 'Walking the lakes is free; only the night cruise is ticketed. Boat prices vary by operator and season. The walk is flat, lit, and safe late into the evening.',
    gallery: [
      { img: 'attraction-tworivers', alt: 'Sun and Moon Pagodas on Shanhu Lake' },
      { img: 'web-tworivers-nightcruise', alt: 'Two Rivers and Four Lakes night cruise' },
      { img: 'web-tworivers-bridge', alt: 'Sun and Moon Pagodas reflection on Shanhu Lake' },
      { img: 'attraction-elephant', alt: 'Elephant Trunk Hill near the lakes' },
      { img: 'web-elephant-night', alt: 'Elephant Trunk Hill at night near the lakes' },
      { img: 'attraction-reedflute', alt: 'Reed Flute Cave near the lakes' },
    ],
    faqs: [
      { q: 'What exactly are the “two rivers and four lakes”?', a: 'The Li River and Peach Blossom River (two rivers) plus Shanhu, Ronghu, Guihu, and Mulong Lake (four lakes) — connected into one water ring around Guilin’s old city center.' },
      { q: 'Is the night cruise worth it?', a: 'Yes, at least once. The lit bridges and the gold-and-silver Sun and Moon Pagodas reflected on the water are the signature Guilin evening, and you see the city from a different angle than the daytime streets.' },
      { q: 'Can I just walk it for free?', a: 'Absolutely. A continuous, flat, free promenade rings all four lakes and both rivers. The boat is optional — the walk is lovely by day and lantern-lit by night.' },
      { q: 'When is the best time to go?', a: 'Dusk. Boats leaving around sunset catch both daylight and the full light show, and the pagodas are most photogenic 20–30 minutes after they switch on.' },
      { q: 'How do I get there?', a: 'The lakes are in the city center, walkable from most hotels. From Elephant Trunk Hill it’s a 10-minute riverside walk north to Shanhu Lake.' },
      { q: 'Is it safe to walk at night?', a: 'Very — the paths are lit, patrolled, and popular with local evening strollers, joggers, and dancers.' },
    ],
    quickFacts: [
      ['System', '2 rivers + 4 lakes'],
      ['Night cruise', '1–2 hours'],
      ['Cruise ticket', '¥210–320'],
      ['Walk', 'Free · flat'],
      ['Best time', 'Dusk → night'],
      ['Location', 'City center'],
      ['Famous for', 'Twin pagodas at night'],
    ],
    localTip: 'Skip the pricey private boat and take the standard public night cruise from Shanhu — same pagodas, same bridges, a fraction of the cost.',
    related: [
      { slug: 'elephant', img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · Walk from here' },
      { slug: 'reedflute', img: 'attraction-reedflute', title: 'Reed Flute Cave', sub: '芦笛岩 · 20 min away' },
      { slug: 'liriver', img: 'hero-liriver', title: 'Li River Cruise', sub: '漓江 · The big river' },
      { slug: 'yangshuo', img: 'attraction-yangshuo', title: 'Yangshuo & West Street', sub: '阳朔 · Countryside' },
    ],
    geo: { lat: 25.275, lng: 110.29 },
  },

  /* ============================ 8. XINGPING ANCIENT TOWN ============================ */
  {
    slug: 'xingping',
    name: 'Xingping Ancient Town',
    cnName: '兴坪古镇',
    kicker: "The 20-Yuan Banknote Village · On the Li River",
    heroImage: 'attraction-xingping',
    ogImage: 'attraction-xingping',
    tagline: '兴坪 · Where the River Makes the Money',
    lead: 'A 1,700-year-old riverside town that happens to sit across from the exact karst bend printed on China’s 20-yuan note. Come for the老街 old street, stay for the slow river life and the sunset over the peaks.',
    glance: '<strong class="text-river">Xingping (兴坪)</strong> is an ancient town on the Li River, about 25&nbsp;km from Yangshuo, that was a county seat over 1,700 years ago. It sits directly across from the karst bend featured on the back of China’s <strong class="text-river">¥20 banknote</strong>. Today it’s a mellow stop of old streets, riverside cafes, and the best low-key base for the most scenic Li River rafting.',
    intro: [
      'Xingping is where the Li River’s fame becomes literal: the bend just across the water is the one on the ¥20 note, and you can stand on the old wharf and see it. The town itself is old — founded in the Three Kingdoms era, it served as a county seat for centuries — and its <strong class="text-river">laojie (老街)</strong> still has Ming- and Qing-dynasty brick houses, though now they hold teahouses and guesthouses rather than granaries.',
      'It’s quieter and cheaper than Yangshuo, which makes it a lovely base. From here the <strong class="text-river">bamboo raft to the 20-yuan view and Nine Horse Hill</strong> is the most scenic Li River section, and the sunsets over the peaks are superb from the waterfront.',
      '<span class="text-sm text-stone-600"><em>Quick tip: to shoot the banknote view, cross to the opposite bank (a short boat or the hiking path) — that’s where the classic composition lines up. In town, arrive late afternoon for golden-hour rooftops and a riverside sundowner.</em></span>',
    ],
    highlights: [
      { img: 'attraction-xingping', title: 'Xingping Ancient Street', sub: '兴坪老街 · Ming–Qing bricks', text: 'A narrow lane of old brick houses, shops, and red flags — the historic heart of the town and a pleasant stroll.' },
      { img: 'web-xingping-bend', title: 'Karst Peaks above Xingping', sub: '兴坪峰丛 · The 20-yuan backdrop', text: 'The limestone towers that line the Li River near Xingping, the same peaks printed on China’s ¥20 note.' },
      { img: 'attraction-liriver', title: 'Riverside Wharf', sub: '码头 · Sunset spot', text: 'The old pier is the place to watch the sun drop behind the limestone towers — and to board rafts.' },
      { img: 'exp-cormorant', title: 'Cormorant Raft Scene', sub: '鸬鹚竹筏 · Li River heritage', text: 'Traditional cormorant fishermen still pole bamboo rafts on the Li River near Xingping — a living postcard.' },
      { img: 'exp-xianggong', title: 'Xianggong Mountain Overlook', sub: '相公山 · Sunrise panorama', text: 'A high viewpoint above the Li River catches dawn light on the karst towers around Xingping.' },
    ],
    routes: [
      {
        icon: 'anchor', title: 'Classic Raft (Xingping → 20-yuan view)', meta: '1–1.5 hours · ¥120–255',
        steps: [
          { t: 'Board at Xingping pier', d: '4-seat bamboo raft, life jackets provided.' },
          { t: 'Glide to the banknote bend', d: 'The exact ¥20 view, slowed for photos.' },
          { t: 'On to Nine Horse Hill', d: 'Count the horses on the cliff face.' },
          { t: 'Return by cart', d: 'Electric cart back to town, included.' },
        ],
      },
      {
        icon: 'ship', title: 'Town + Opposite Bank', meta: 'Half day · on foot + boat',
        steps: [
          { t: 'Walk the old street', d: 'Ming–Qing brick lane, teahouses, and the old wharf.' },
          { t: 'Cross to the view bank', d: 'Short boat or hiking path to the ¥20 composition.' },
          { t: 'Sunset on the wharf', d: 'Riverside sundowner as the peaks glow.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'Apr – May', text: 'Green peaks, misty river, soft light for the banknote shot.' },
      { icon: 'calendar-heart', title: 'Sep – Nov', text: 'Clear skies and golden-hour sunsets — the most popular time.' },
      { icon: 'sun', title: 'Late afternoon', text: 'Arrive by 4 PM for golden rooftops and the riverside sunset.' },
    ],
    tips: [
      { icon: 'clock', title: 'Cross for the real view', text: 'The ¥20 composition lines up from the opposite bank, not from town. Take the small boat across.' },
      { icon: 'camera', title: 'Shoot at golden hour', text: 'The old street bricks and the peaks glow 1 hour before sunset — best light of the day.' },
      { icon: 'sun', title: 'Stay overnight', text: 'Xingping is calm and cheap; a guesthouse lets you catch dawn mist on the river.' },
      { icon: 'utensils', title: 'Eat by the water', text: 'Riverside spots serve beer fish and simple noodles with the view.' },
      { icon: 'droplet', title: 'Rafts pause in rain', text: 'Heavy rain stops rafting; ask locally before you go.' },
    ],
    gettingThere: [
      { t: 'From Yangshuo', d: 'About 25 km; bus (40 min, ¥10–15) or taxi (¥60–80).' },
      { t: 'From Guilin', d: 'Bus to Yangshuo then Xingping, or a direct tour (~2 h).' },
      { t: 'By Li River cruise', d: 'The big cruise passes Xingping; some travelers hop off here instead of continuing to Yangshuo.' },
      { t: 'Tickets', d: 'Town is free; raft tickets at the pier or via your hotel.' },
    ],
    tickets: [
      ['Town entry', 'Free'],
      ['Bamboo raft (to 20-yuan view)', '¥120–255'],
      ['From Yangshuo', '25 km · 40 min'],
      ['Best months', 'April–May · Sep–Nov'],
      ['Best time', 'Late afternoon'],
      ['Stay', '1 night recommended'],
    ],
    ticketNote: 'Wandering Xingping is free; only the raft is ticketed. Raft prices are reference values and rise in peak season. Rafts pause during heavy rain. Bring your passport — it may be checked at the pier.',
    gallery: [
      { img: 'attraction-xingping', alt: 'Xingping ancient street' },
      { img: 'web-xingping-bend', alt: 'Karst peaks above the Li River near Xingping' },
      { img: 'attraction-liriver', alt: 'Xingping riverside wharf on the Li River' },
      { img: 'exp-cormorant', alt: 'Cormorant fisherman on the Li River near Xingping' },
      { img: 'exp-xianggong', alt: 'Xianggong Mountain overlook of the Li River near Xingping' },
      { img: 'attraction-yangshuo', alt: 'Yangshuo West Street — a nearby base for Xingping' },
    ],
    faqs: [
      { q: 'Is the 20-yuan view actually here?', a: 'Yes. The karst bend on the back of China’s ¥20 note is directly across the river from Xingping. To get the exact framing, cross to the opposite bank — the composition doesn’t line up from the town side.' },
      { q: 'How is Xingping different from Yangshuo?', a: 'Xingping is smaller, older, quieter, and cheaper, and it’s right at the most scenic Li River rafting section. Yangshuo is bigger, livelier, and better for nightlife and biking. Many travelers stay in one and day-trip the other.' },
      { q: 'How do I get to Xingping?', a: 'About 25 km from Yangshuo: a bus (40 min, ¥10–15) or taxi (¥60–80). From Guilin it’s roughly 2 hours by bus or tour. The big Li River cruise also passes through.' },
      { q: 'Is it worth staying overnight?', a: 'Yes if you want calm and good light. A guesthouse lets you catch dawn mist on the river and the golden-hour rooftops without the day-tripper rush.' },
      { q: 'What’s the best raft here?', a: 'The Xingping-to-20-yuan-view (and Nine Horse Hill) raft is the Li River’s highlight reel — 1–1.5 hours, close to the water, and far cheaper than the full cruise.' },
      { q: 'Can I walk the old street easily?', a: 'Yes — it’s a short, flat lane of Ming–Qing brick houses with teahouses and shops. Fully walkable, no ticket needed.' },
    ],
    quickFacts: [
      ['Age', '1,700+ years'],
      ['From Yangshuo', '25 km · 40 min'],
      ['Town entry', 'Free'],
      ['Best season', 'Apr–May · Sep–Nov'],
      ['Raft', '¥120–255'],
      ['Stay', '1 night'],
      ['Famous for', '¥20 banknote view'],
    ],
    localTip: 'Everyone clusters on the town-side wharf for the “banknote photo” and misses it. Take the little boat across the river — that’s where the note’s composition actually lines up.',
    related: [
      { slug: 'liriver', img: 'hero-liriver', title: 'Li River Cruise', sub: '漓江 · The view is from here' },
      { slug: 'yangshuo', img: 'attraction-yangshuo', title: 'Yangshuo & West Street', sub: '阳朔 · 40 min away' },
      { slug: 'yulong', img: 'attraction-yulong', title: 'Yulong River Rafting', sub: '遇龙河 · Nearby' },
      { slug: 'elephant', img: 'attraction-elephant', title: 'Elephant Trunk Hill', sub: '象鼻山 · Guilin city' },
    ],
    geo: { lat: 24.90, lng: 110.43 },
  },
];
