// experiences-data.mjs
// Single source of truth for all 8 "Experiences You Can't Miss" detail pages.
// Consumed by scripts/build-experiences.mjs -> renders experiences/*.html

export const SITE = {
  name: 'Visit Guilin',
  url: 'https://myguilin.com',
  phone: '+86 187 7735 8302',
  whatsapp: '8618777358302',
  email: 'willyumi2026@outlook.com',
};

export const experiences = [
  /* ============================== 1. LI RIVER CRUISE ============================== */
  {
    slug: 'li-river-cruise',
    cardId: 'exp-liriver',
    name: 'Li River Cruise',
    cnName: '漓江游船',
    kicker: "China's Most Famous Scenic River Journey · Guilin to Yangshuo",
    heroImage: 'exp-liriver',
    ogImage: 'exp-liriver',
    tagline: '漓江游船 · The journey every visitor to Guilin should take once',
    lead: 'Cruise 83 kilometers through the world’s most famous karst landscape — the same scenery printed on China’s 20-yuan note, passing cormorant fishermen, bamboo groves, and villages unchanged for centuries.',
    glance: '<strong class="text-river">The Li River Cruise</strong> is the single most iconic experience in Guilin. The 4–5 hour downstream journey from Guilin’s Zhujiang Pier to Yangshuo covers 83 km of scenery that has inspired Chinese painters for over a thousand years.',
    intro: [
      'If you only do one thing in Guilin, make it this. The Li River cruise is not a tourist trap — it is the reason Guilin became famous in the first place. For 83 kilometers, the river winds through a landscape of sugar-loaf limestone peaks, bamboo groves, and water-buffalo fields that looks almost too perfect to be real.',
      'The boats depart from Zhujiang Pier, about 40 minutes south of Guilin city, and arrive in Yangshuo in time for a late lunch. Along the way you pass the famous <strong class="text-river">Nine Horse Fresco Hill</strong>, the <strong class="text-river">20-yuan banknote view</strong> near Xingping, and cormorant fishermen poling bamboo rafts. The cruise is one-way (Guilin → Yangshuo), so most travelers stay in Yangshuo or take a bus back.',
      '<span class="text-sm text-stone-600"><em>Local tip: The upper deck is worth the small upgrade. Morning departures have the best light and fewer crowds. Bring snacks — the included lunch is basic.</em></span>',
    ],
    highlights: [
      { img: 'exp-liriver', title: 'The Classic River View', sub: '漓江全景 · Karst peaks from the water', text: 'The sweeping river corridor that appears on countless postcards, China’s ¥20 note, and the cover of every Guilin travel guide.' },
      { img: 'exp-liriver-1', title: 'Nine Horse Fresco Hill', sub: '九马画山 · Count the horses', text: 'A 100-meter cliff face that locals say contains nine horses hidden in its patterns — most visitors spot three or four.' },
      { img: 'exp-cormorant', title: 'Cormorant Fishermen at Work', sub: '鸬鹚渔夫 · Living tradition', text: 'Traditional fishermen still pole bamboo rafts with trained cormorants along the river, especially at dusk near Xingping.' },
      { img: 'exp-liriver-2', title: 'Xingping Riverfront', sub: '兴坪码头 · The 20-yuan view', text: 'The bend near Xingping is the exact scene printed on the back of China’s 20-yuan banknote — the most photographed stretch of the river.' },
      { img: 'exp-xianggong', title: 'Xianggong Mountain Overlook', sub: '相公山 · Sunrise panorama', text: 'From the summit above the river, you can see the entire Li River corridor wrapped in morning mist and golden light.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Full Cruise (Recommended)', meta: '4–5 hours · Guilin → Yangshuo · ¥300–500',
        steps: [
          { t: 'Board at Zhujiang Pier', d: 'About 40 minutes from Guilin city center by taxi or transfer.' },
          { t: 'Cruise past Crown Cave', d: 'The first dramatic karst formation along the route.' },
          { t: 'See Nine Horse Fresco Hill', d: 'Count the horses in the cliff face as the guide points them out.' },
          { t: 'Photo stop at the 20-yuan view', d: 'The boat slows near Xingping for the iconic shot.' },
          { t: 'Arrive in Yangshuo', d: 'Disembark, explore West Street, or return to Guilin by bus.' },
        ],
      },
      {
        icon: 'anchor', title: 'Bamboo Raft (Short & Sweet)', meta: '1–1.5 hours · Xingping section · ¥120–255',
        steps: [
          { t: 'Get to Xingping', d: 'Bus from Yangshuo (40 min) or Guilin (2 hrs).' },
          { t: 'Board a 4-seat raft', d: 'Motorized PVC raft with life jackets — stable and safe.' },
          { t: 'Pass the 20-yuan view', d: 'The most scenic 1-hour stretch of the whole river.' },
          { t: 'Return by electric cart', d: 'Included in most tickets.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'April – May', text: 'Warm, green, and often misty — the most photogenic season.' },
      { icon: 'calendar-heart', title: 'September – November', text: 'Clear skies, crisp air, and golden rice fields along the banks.' },
      { icon: 'cloud-rain', title: 'After light rain', text: 'Mist rises between the peaks, creating the classic ink-wash effect.' },
    ],
    tips: [
      { icon: 'clock', title: 'Book morning departures', text: '8:30–9:30 AM boats have the best light and fewer crowds.' },
      { icon: 'sun', title: 'Sun protection is essential', text: 'The upper deck has no shade. Hat, sunscreen, and sunglasses are must-haves.' },
      { icon: 'camera', title: 'Pay for the upper deck', text: 'Usually ¥20–50 extra, but the unobstructed views and breeze are worth it.' },
      { icon: 'utensils', title: 'Pack your own snacks', text: 'The included lunch is simple. Bring water, fruit, and crackers.' },
      { icon: 'droplet', title: 'Check water levels', text: 'Cruises may be suspended during summer floods or winter dry spells.' },
    ],
    gettingThere: [
      { t: 'Get to Zhujiang Pier', d: 'Taxi or transfer from Guilin city (40 min, ¥80–120). Public bus #9 is cheaper but slower.' },
      { t: 'Book tickets in advance', d: 'Foreign travelers should book through hotels or agencies at least one day ahead — the pier has no walk-up window for non-Chinese speakers.' },
      { t: 'Bring your passport', d: 'It is checked at the pier before boarding.' },
      { t: 'Return from Yangshuo', d: 'Buses to Guilin run until about 18:30 (90 min, ¥25–30). A taxi back costs ¥150–200.' },
    ],
    tickets: [
      ['Full cruise (Guilin → Yangshuo)', '¥300–500 — includes simple lunch; 3- or 4-star boat options'],
      ['Bamboo raft (Xingping section)', '¥120–255 — 4 people per raft; best 1-hour highlight'],
      ['Upper-deck upgrade', '¥20–50 — optional, cash on board'],
      ['Departure times', '8:30, 9:00, 9:30 AM (seasonal)'],
      ['Cruise duration', '4–5 hours (83 km downstream)'],
      ['Best months', 'April–May, September–November'],
    ],
    ticketNote: 'Prices are reference values for international travelers. Rafts may stop during heavy rain or flood warnings. Always confirm the schedule with your hotel or guide the day before.',
    gallery: [
      { img: 'exp-liriver', alt: 'Li River cruise boats winding through karst peaks' },
      { img: 'exp-liriver-1', alt: 'Nine Horse Fresco Hill cliff face' },
      { img: 'exp-cormorant', alt: 'Cormorant fisherman on a bamboo raft at dusk' },
      { img: 'exp-liriver-2', alt: 'Xingping riverfront and the 20-yuan view' },
      { img: 'exp-xianggong', alt: 'Sunrise over the Li River from Xianggong Mountain' },
      { img: 'web-yangshuo-countryside', alt: 'Cruise boats and karst peaks on a clear day' },
    ],
    faqs: [
      { q: 'How long is the Li River cruise, and where does it start?', a: 'The classic cruise is 83 km (about 4–5 hours) from Zhujiang Pier near Guilin to Yangshuo. Boats depart between 8:30 and 9:30 AM and arrive in Yangshuo around 1:30–2:30 PM.' },
      { q: 'Is the ¥20 banknote view really on the cruise?', a: 'Yes — the iconic scene on the back of China’s 20-yuan note is near Xingping, about two-thirds of the way down the river. The cruise slows for photos, and the same view is also reachable by the shorter Xingping bamboo raft.' },
      { q: 'What is the difference between the cruise and the bamboo raft?', a: 'The full cruise is a 4–5 hour motorized boat covering the entire 83 km route with a simple lunch included. The bamboo raft is a shorter 1–1.5 hour motorized PVC raft on the most scenic Xingping section, closer to the water and usually less crowded.' },
      { q: 'Can I book a same-day cruise ticket?', a: 'Not reliably. There is no convenient walk-up ticket office for foreign travelers at the pier. Book through your hotel, a travel agency, or online at least one day ahead, especially during peak seasons.' },
      { q: 'What happens if the weather is bad?', a: 'Light rain is fine and can make the scenery more atmospheric. Heavy rain or flood warnings may suspend the cruise or raft service. Always check with your guide or hotel the day before.' },
      { q: 'Should I stay in Guilin or Yangshuo after the cruise?', a: 'Most travelers prefer to stay in Yangshuo. It is small, walkable, and surrounded by karst peaks. After the cruise you can bike the countryside, raft the Yulong River, or explore West Street. Guilin is better for airport/train connections.' },
    ],
    quickFacts: [
      ['Distance', '83 km'],
      ['Duration', '4–5 hours'],
      ['Best season', 'Apr–May · Sep–Nov'],
      ['Route', 'Guilin → Yangshuo'],
      ['Price range', '¥300–500'],
      ['Departure', 'Zhujiang Pier'],
      ['Famous for', '¥20 note view'],
    ],
    localTip: 'Skip the crowded 4-star cruise and take the Xingping bamboo raft instead. You see the same 20-yuan view from closer to the water, for half the price, with fewer people. Then spend the afternoon cycling through Yangshuo’s countryside.',
    related: [
      { slug: 'bamboo-rafting', img: 'exp-bamboo', title: 'Bamboo Rafting', sub: 'Yulong River · Quiet alternative' },
      { slug: 'countryside-cycling', img: 'exp-cycling', title: 'Countryside Cycling', sub: 'Yangshuo · Flat trails' },
      { slug: 'cormorant-fishing', img: 'exp-cormorant', title: 'Cormorant Fishing', sub: 'Xingping · Dusk tradition' },
    ],
    geo: { lat: 25.07, lng: 110.32 },
  },

  /* ============================== 2. COUNTRYSIDE CYCLING ============================== */
  {
    slug: 'countryside-cycling',
    cardId: 'exp-cycling',
    name: 'Countryside Cycling',
    cnName: '阳朔乡村骑行',
    kicker: 'Pedal Through Rice Fields and Karst Peaks Around Yangshuo',
    heroImage: 'exp-cycling',
    ogImage: 'exp-cycling',
    tagline: '阳朔骑行 · The best way to see the real Yangshuo',
    lead: 'Rent a bike and ride flat country lanes through emerald rice paddies, past water buffalo, and beneath towering karst peaks — the most human-scale way to experience Yangshuo.',
    glance: '<strong class="text-river">Countryside cycling</strong> is the perfect low-effort, high-reward activity in Yangshuo. The trails are flat, the scenery is endless, and you can stop whenever a village, view, or roadside fruit stall catches your eye.',
    intro: [
      'Yangshuo looks good from a bus window, but it looks unforgettable from a bicycle seat. The countryside around the town is a patchwork of rice paddies, lotus ponds, bamboo groves, and small villages, all framed by limestone towers that rise straight up from the flat valley floor.',
      'The cycling routes are mostly flat, paved or hard-packed, and easy to follow. You do not need to be fit. You can rent a bike or e-bike for ¥20–50 per day, pick up a simple map from your hostel, and spend half a day exploring at your own pace. The most popular loop runs from Yangshuo town along the Yulong River to <strong class="text-river">Moon Hill</strong> and <strong class="text-river">Dragon Bridge</strong>.',
      '<span class="text-sm text-stone-600"><em>Local tip: Start early, before 9 AM. The light is soft, the air is cool, and the main roads are still quiet. Bring cash for cold drinks at village shops.</em></span>',
    ],
    highlights: [
      { img: 'exp-cycling', title: 'Rice Paddy Backroads', sub: '稻田小路 · Flat and green', text: 'Pedal narrow lanes between emerald rice paddies, where farmers work with water buffalo and the only traffic is an occasional scooter.' },
      { img: 'exp-cycling-1', title: 'Yulong River Valley', sub: '遇龙河谷 · Riverside trails', text: 'Follow the river on quiet paths, crossing old stone bridges and passing bamboo rafts floating downstream.' },
      { img: 'exp-cycling-2', title: 'Moon Hill', sub: '月亮山 · The natural arch', text: 'A karst tower with a perfect moon-shaped hole through the top — the turnaround point for the classic half-day loop.' },
      { img: 'exp-cycling-3', title: 'Dragon Bridge', sub: '遇龙桥 · 600-year-old stone bridge', text: 'One of the oldest and most beautiful bridges in the region, built during the Ming dynasty over the Yulong River.' },
      { img: 'exp-cycling-4', title: 'Village Life', sub: '农家 · Real Yangshuo', text: 'Stop at a roadside farm stand for fresh sugarcane juice, or watch farmers transplant rice seedlings in flooded spring fields.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Yulong River Half-Day Loop', meta: '15–20 km · 3–4 hours · easy',
        steps: [
          { t: 'Rent a bike in Yangshuo', d: 'West Street area has many shops (¥20–50/day).' },
          { t: 'Head south on Chaoyang Road', d: 'Follow the signs toward the Yulong River.' },
          { t: 'Cycle to Dragon Bridge', d: 'The oldest stone bridge on the river — great photo stop.' },
          { t: 'Turn around at Moon Hill', d: 'Optional 20-minute climb to the arch viewpoint.' },
          { t: 'Return along the other bank', d: 'A different view of the same beautiful valley.' },
        ],
      },
      {
        icon: 'anchor', title: 'Short & Easy Town-to-Country Loop', meta: '8–10 km · 1.5–2 hours · very easy',
        steps: [
          { t: 'Start from West Street', d: 'Rent a bike and head east out of town.' },
          { t: 'Follow the rural lanes', d: 'Flat paths through rice fields and small villages.' },
          { t: 'Stop at a village cafe', d: 'Rest and refuel with fresh fruit or sugarcane juice.' },
          { t: 'Loop back to Yangshuo', d: 'Return the bike before sunset.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'April – May', text: 'Rice fields are flooded and mirror-like; green shoots everywhere.' },
      { icon: 'calendar-heart', title: 'September – October', text: 'Golden rice harvest season — warm light and dry paths.' },
      { icon: 'sun', title: 'Early morning', text: 'Start before 9 AM to avoid heat, traffic, and tour groups.' },
    ],
    tips: [
      { icon: 'clock', title: 'Start early', text: 'Morning light is best and the main roads are quiet.' },
      { icon: 'sun', title: 'Bring sun protection', text: 'There is little shade in the rice fields. Hat, sunscreen, and sunglasses are essential.' },
      { icon: 'camera', title: 'Stop often', text: 'The best moments are unplanned — a farmer, a water buffalo, a perfect reflection.' },
      { icon: 'utensils', title: 'Carry cash and water', text: 'Small village shops may not take cards or digital payment.' },
      { icon: 'droplet', title: 'Watch for rain', text: 'Country lanes can get muddy after heavy rain. E-bikes handle puddles better than bicycles.' },
    ],
    gettingThere: [
      { t: 'Get to Yangshuo', d: 'From Guilin by bus (1.5 hrs, ¥25–35) or after the Li River cruise (disembark in Yangshuo).' },
      { t: 'Rent a bike', d: 'Dozens of rental shops along West Street and Baisha Road. E-bikes cost slightly more but are effortless.' },
      { t: 'Pick up a map', d: 'Most hotels and hostels provide a simple cycling map with the main loop marked.' },
      { t: 'Return the bike', d: 'Most shops open until 6–7 PM. Plan to be back before sunset.' },
    ],
    tickets: [
      ['Bicycle rental', '¥20–40/day — standard mountain bike'],
      ['E-bike rental', '¥40–80/day — easier on hills and heat'],
      ['Guided cycling tour', '¥200–400/person — includes bike, guide, and village lunch'],
      ['Moon Hill entry', '¥15 — optional climb to the arch viewpoint'],
      ['Best duration', 'Half day (3–4 hours) or full day'],
      ['Route difficulty', 'Easy — mostly flat, suitable for all ages'],
    ],
    ticketNote: 'Prices are reference values. No advance booking is needed for bike rental — just walk into any shop on West Street. Bring a photo ID as a deposit.',
    gallery: [
      { img: 'exp-cycling', alt: 'Cycling through rice fields near Yangshuo' },
      { img: 'exp-cycling-1', alt: 'Yulong River valley cycling path' },
      { img: 'exp-cycling-2', alt: 'Moon Hill natural arch' },
      { img: 'exp-cycling-3', alt: 'Dragon Bridge over the Yulong River' },
      { img: 'exp-cycling-4', alt: 'Village life in the Yangshuo countryside' },
      { img: 'web-yulong-karst', alt: 'Aerial view of Yangshuo karst peaks' },
    ],
    faqs: [
      { q: 'Do I need to be fit to cycle in Yangshuo?', a: 'No. Most routes are flat and easy. The classic Yulong River loop is about 15–20 km with almost no hills. E-bikes are widely available if you want to make it effortless.' },
      { q: 'Where can I rent a bike?', a: 'Bike rental shops are everywhere along West Street and the main roads in Yangshuo. Prices are ¥20–40 for a standard bike and ¥40–80 for an e-bike per day.' },
      { q: 'What is the best cycling route?', a: 'The most popular half-day route follows the Yulong River from Yangshuo to Dragon Bridge and Moon Hill, then loops back on the opposite bank. It offers rice fields, karst peaks, and riverside views without heavy traffic.' },
      { q: 'Can I combine cycling with bamboo rafting?', a: 'Yes — many travelers raft down the Yulong River, then have a bike delivered to the take-out point and cycle back to Yangshuo. Ask your hotel or raft operator to arrange it.' },
      { q: 'Is it safe to cycle on the main roads?', a: 'Stick to the rural lanes and riverside paths. The main highways can be busy with buses and cars. Early morning is safest and most peaceful.' },
      { q: 'What should I bring?', a: 'Sunscreen, a hat, sunglasses, water, cash, and a phone for navigation. Most importantly, a relaxed pace — the best stops are the ones you did not plan.' },
    ],
    quickFacts: [
      ['Distance', '15–20 km typical'],
      ['Duration', 'Half day to full day'],
      ['Best season', 'Apr–May · Sep–Oct'],
      ['Difficulty', 'Easy / flat'],
      ['Bike rental', '¥20–40/day'],
      ['E-bike rental', '¥40–80/day'],
      ['Highlights', 'Yulong River · Moon Hill · Dragon Bridge'],
    ],
    localTip: 'Rent an e-bike, not a regular bike. The routes are flat but the heat and sun can drain you. An e-bike lets you go further, stop more often, and still feel fresh at the end of the day.',
    related: [
      { slug: 'bamboo-rafting', img: 'exp-bamboo', title: 'Bamboo Rafting', sub: 'Yulong River · Combine with cycling' },
      { slug: 'rock-climbing', img: 'exp-climb', title: 'Rock Climbing', sub: 'Yangshuo · Active adventure' },
      { slug: 'cooking-class', img: 'exp-cook', title: 'Cooking Class', sub: 'Yangshuo · Food culture' },
    ],
    geo: { lat: 24.78, lng: 110.49 },
  },

  /* ============================== 3. LONGJI TERRACES TREK ============================== */
  {
    slug: 'longji-terraces-trek',
    cardId: 'exp-longji',
    name: 'Longji Terraces Trek',
    cnName: '龙脊梯田徒步',
    kicker: 'Hike Among Mirror-Like Rice Terraces and Minority Villages',
    heroImage: 'exp-longji',
    ogImage: 'exp-longji',
    tagline: '龙脊梯田 · Where mountain farmers have sculpted the hills for 800 years',
    lead: 'Walk layered rice terraces that climb like stairways into the clouds, passing wooden villages of the Zhuang and Yao people, with sunrise views over a sea of mist.',
    glance: '<strong class="text-river">The Longji Rice Terraces</strong> are one of China’s most impressive man-made landscapes. A trek here is a mix of gentle hiking, village exploration, and some of the best sunrise photography in southern China.',
    intro: [
      'The Longji Rice Terraces, also known as the Dragon’s Backbone Terraces, are not just beautiful — they are a 650-year-old feat of engineering. Built by Zhuang and Yao minority communities, the terraces turn the steep mountainsides into a cascading pattern of water, rice, and sky.',
      'A trek here is less about reaching a summit and more about walking through the landscape itself. The trails connect villages like <strong class="text-river">Ping’an</strong> and <strong class="text-river">Dazhai</strong> via stone paths that pass guesthouses, small shops, and viewpoints. Some sections are steep, but the pace is slow and the scenery rewards every step.',
      '<span class="text-sm text-stone-600"><em>Local tip: Stay overnight in a wooden guesthouse inside the terraces. The sunrise and sunset are the real highlights, and day-trippers miss the best light.</em></span>',
    ],
    highlights: [
      { img: 'exp-longji', title: 'Layered Rice Terraces', sub: '千层梯田 · Mirror steps', text: 'Flooded terraces reflect the sky in spring; in autumn they turn gold. The patterns change completely with the season.' },
      { img: 'exp-longji-1', title: 'Sunrise Over the Sea of Clouds', sub: '云海日出 · Dawn from the ridges', text: 'From viewpoints like Golden Buddha or Thousand-Layer, the morning light turns the terraces into bands of gold and silver.' },
      { img: 'exp-longji-2', title: 'Zhuang and Yao Villages', sub: '壮寨瑶寨 · Wooden mountain homes', text: 'Traditional wooden houses cling to the hillsides, with minority women in hand-embroidered clothing selling crafts and snacks.' },
      { img: 'exp-longji-3', title: 'Stone Pathways', sub: '石板路 · Ancient trails', text: 'The trekking paths are paved with local stone, sometimes centuries old, winding between fields and forests.' },
      { img: 'exp-longji-4', title: 'Water Buffalo and Farmers', sub: '田间劳作 · Living agriculture', text: 'Farmers still plant and harvest by hand here. You may see water buffalo plowing, ducks in the paddies, and families transplanting rice.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Ping’an Village Loop', meta: '4–5 hours · moderate · circular',
        steps: [
          { t: 'Enter at the main gate', d: 'Buy a ticket and take the shuttle bus to Ping’an village.' },
          { t: 'Hike to Seven Stars and Moon Viewpoint', d: 'About 40 minutes of stone steps up the ridge.' },
          { t: 'Continue to Thousand-Layer Terraces', d: 'The most dramatic wide-angle view of the terraces.' },
          { t: 'Loop back through Zhongliu village', d: 'A quieter path with fewer tourists.' },
          { t: 'Return to Ping’an', d: 'Rest with tea and sweet rice cakes at a local guesthouse.' },
        ],
      },
      {
        icon: 'anchor', title: 'Ping’an to Dazhai Trek', meta: '6–7 hours · challenging · one-way',
        steps: [
          { t: 'Start in Ping’an', d: 'Begin early, around 7:30 AM.' },
          { t: 'Cross the ridges between villages', d: 'A full traverse of the terraced mountains.' },
          { t: 'Pass Tiantouzhai village', d: 'Halfway point with basic snack stops.' },
          { t: 'End at Dazhai', d: 'Famous for the Golden Buddha Summit viewpoint.' },
          { t: 'Stay overnight or shuttle back', d: 'Dazhai has guesthouses and a shuttle bus to the parking lot.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'April – May', text: 'Terraces are flooded and mirror-like; planting season brings lush greens.' },
      { icon: 'calendar-heart', title: 'Late September – October', text: 'Golden harvest season — the most photogenic and busiest time.' },
      { icon: 'sun', title: 'Winter', text: 'Fewer visitors and stark, sculptural terraces after the harvest.' },
    ],
    tips: [
      { icon: 'clock', title: 'Stay overnight', text: 'Day trips miss sunrise and sunset — the best parts of the experience.' },
      { icon: 'sun', title: 'Expect lots of steps', text: 'There are stone steps everywhere. Trekking poles help, especially on the descent.' },
      { icon: 'camera', title: 'Book a sunrise-view guesthouse', text: 'Stay near a viewpoint so you can roll out of bed for the dawn light.' },
      { icon: 'utensils', title: 'Try bamboo rice and home cooking', text: 'Local guesthouses serve simple, fresh meals made with ingredients from the terraces.' },
      { icon: 'droplet', title: 'Check the weather', text: 'Fog can hide the views, but it also creates dramatic sea-of-clouds scenes.' },
    ],
    gettingThere: [
      { t: 'From Guilin to Longji', d: 'Direct bus or private transfer (2–2.5 hours, ¥50–80 per person by bus).' },
      { t: 'Buy the entry ticket', d: '¥80–90 at the main gate; the shuttle bus to the villages is included.' },
      { t: 'Choose a base village', d: 'Ping’an is more accessible and compact; Dazhai is more remote with bigger views.' },
      { t: 'Stay overnight', d: 'Book a wooden guesthouse in advance during peak season (May and October).' },
    ],
    tickets: [
      ['Longji entry ticket', '¥80–90 — includes shuttle bus to villages'],
      ['Guilin – Longji bus', '¥50–80 — one way, 2–2.5 hours'],
      ['Private transfer', '¥400–600 — car/van from Guilin, more flexible'],
      ['Guesthouse (mid-range)', '¥150–300/night — wooden rooms with valley views'],
      ['Guided trek', '¥200–400/person — half-day with local guide'],
      ['Best duration', '2 days / 1 night minimum'],
    ],
    ticketNote: 'Prices are reference values. Longji is best experienced with an overnight stay. Entry tickets are valid for the duration of your stay.',
    gallery: [
      { img: 'exp-longji', alt: 'Longji rice terraces in golden light' },
      { img: 'exp-longji-1', alt: 'Sunrise over the Longji terraces' },
      { img: 'exp-longji-2', alt: 'Zhuang village houses on the hillside' },
      { img: 'exp-longji-3', alt: 'Stone pathway between rice terraces' },
      { img: 'exp-longji-4', alt: 'Water buffalo in the terraced fields' },
      { img: 'web-longji-jinkeng', alt: 'Wide view of Jinkeng rice terraces' },
    ],
    faqs: [
      { q: 'How long should I spend at Longji?', a: 'At least one night. The sunrise and sunset are the highlights, and the trails are best explored without rushing. Two days and one night is ideal for most travelers.' },
      { q: 'Is the hiking difficult?', a: 'The Ping’an village loop is moderate with many stone steps. The Ping’an to Dazhai trek is challenging and long. Most travelers can handle the loop with reasonable fitness and good shoes.' },
      { q: 'What is the best time to visit the terraces?', a: 'April–May for flooded, mirror-like terraces and fresh green; late September–October for golden harvest. Winter is quiet but the terraces are bare. Summer is lush green but hot and humid.' },
      { q: 'Can I visit Longji as a day trip from Guilin?', a: 'Yes, but it is not recommended. The drive is 2–2.5 hours each way, so you would only have a few hours on the mountain. You would miss sunrise, sunset, and the peaceful evening atmosphere.' },
      { q: 'Do I need a guide?', a: 'Not for the main Ping’an loop, which is well marked. For the Ping’an to Dazhai traverse or off-trail viewpoints, a local guide is helpful and supports the village economy.' },
      { q: 'What should I pack?', a: 'Good walking shoes, layers for cool mornings, rain gear, sunscreen, and a small daypack. Trekking poles are useful for the stone steps.' },
    ],
    quickFacts: [
      ['Elevation', '350–1,100 m'],
      ['Duration', 'Half day to 2 days'],
      ['Best season', 'Apr–May · Sep–Oct'],
      ['Difficulty', 'Moderate to challenging'],
      ['Entry fee', '¥80–90'],
      ['Base villages', 'Ping’an · Dazhai'],
      ['Highlights', 'Sunrise · terraces · villages'],
    ],
    localTip: 'Stay at a guesthouse near the Seven Stars and Moon viewpoint in Ping’an. Wake up 20 minutes before sunrise, walk to the viewpoint in your slippers, and watch the terraces turn gold as the fog lifts.',
    related: [
      { slug: 'countryside-cycling', img: 'exp-cycling', title: 'Countryside Cycling', sub: 'Yangshuo · Flat & scenic' },
      { slug: 'sunrise-viewpoint', img: 'exp-xianggong', title: 'Sunrise Viewpoint', sub: 'Xianggong Hill · Dawn panorama' },
      { slug: 'li-river-cruise', img: 'exp-liriver', title: 'Li River Cruise', sub: 'Guilin → Yangshuo · Classic' },
    ],
    geo: { lat: 25.73, lng: 110.07 },
  },

  /* ============================== 4. CORMORANT FISHING ============================== */
  {
    slug: 'cormorant-fishing',
    cardId: 'exp-cormorant',
    name: 'Cormorant Fishing',
    cnName: '漓江鸬鹚捕鱼',
    kicker: 'Watch a Centuries-Old Fishing Tradition at Dusk on the Li River',
    heroImage: 'exp-cormorant',
    ogImage: 'exp-cormorant',
    tagline: '鸬鹚夜捕 · A living postcard from old China',
    lead: 'At sunset, a fisherman in a bamboo hat lights a lantern on his raft, and trained cormorants dive into the dark water — a scene that has played out on the Li River for more than a thousand years.',
    glance: '<strong class="text-river">Cormorant fishing</strong> is one of the most atmospheric experiences in Guilin. It is not a performance in a theater — it happens on the river, at dusk, and the best way to see it is from a boat or the Xingping riverfront.',
    intro: [
      'Cormorant fishing was once common across southern China. Today, it survives mainly as a cultural tradition around the Li River near Xingping. The fishermen use trained cormorants — birds that dive underwater and catch fish in their beaks, but cannot swallow them because of a ring tied around their necks.',
      'The scene is most magical at dusk. The fisherman lights a <strong class="text-river">gas lamp</strong> on his bamboo raft, the water turns silver, and the birds slip in and out of the dark river. For photographers, it is one of the most sought-after shots in Guilin. For everyone else, it is a quiet, human connection to a way of life that is slowly disappearing.',
      '<span class="text-sm text-stone-600"><em>Local tip: The fishing is not staged for tourists every evening. The best chance to see it is to arrange a private boat at sunset from Xingping, or book a photography tour that works with local fishermen.</em></span>',
    ],
    highlights: [
      { img: 'exp-cormorant', title: 'Lantern Light on the River', sub: '渔灯 · The golden glow of dusk', text: 'As the sun sets, the fisherman lights a lantern on the raft, turning the river into a stage of warm light and shadow.' },
      { img: 'exp-cormorant-1', title: 'Trained Cormorants', sub: '鸬鹚 · Working birds', text: 'These sleek black birds are trained from youth to catch fish and return them to the raft — a partnership that can last a decade.' },
      { img: 'exp-cormorant-2', title: 'Bamboo Raft Heritage', sub: '竹筏 · Traditional craft', text: 'The fisherman poles a narrow bamboo raft, often wearing a straw rain cape and bamboo hat — the classic image of old China.' },
      { img: 'exp-cormorant-3', title: 'The Xingping Riverfront', sub: '兴坪 · Best place to see it', text: 'Xingping’s quiet waterfront is the traditional home of cormorant fishing on the Li River, away from the bigger cruise boats.' },
      { img: 'exp-cormorant-4', title: 'Photography at Blue Hour', sub: '蓝调时刻 · Best light', text: 'The 20 minutes after sunset, when the sky is deep blue and the lantern is warm, is the most beautiful time to watch.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Private Boat from Xingping', meta: '1.5–2 hours · sunset · ¥150–400',
        steps: [
          { t: 'Arrive in Xingping', d: 'By bus from Yangshuo (40 min) or Guilin (2 hrs).' },
          { t: 'Walk to the riverfront', d: 'Small boats and local fishermen gather near the Xingping pier.' },
          { t: 'Negotiate a private boat', d: 'Arrange a cormorant-fishing demonstration at sunset.' },
          { t: 'Watch from the water', d: 'The boat follows the raft as the fisherman works the birds.' },
          { t: 'Return after dark', d: 'Xingping has restaurants for dinner before you head back.' },
        ],
      },
      {
        icon: 'anchor', title: 'Photography Tour', meta: '2–3 hours · sunrise or sunset · ¥300–800',
        steps: [
          { t: 'Book with a local guide', d: 'Guides who know the fishermen can arrange the best angles.' },
          { t: 'Meet at the riverbank', d: 'Usually near Xingping or along the Li River banks.' },
          { t: 'Shoot during golden hour', d: 'Sunset is most popular, but sunrise is quieter and mistier.' },
          { t: 'Respect the tradition', d: 'Keep a polite distance and avoid using flash.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'March – November', text: 'Longer days and warmer evenings make dusk sessions comfortable.' },
      { icon: 'sun', title: 'Sunset', text: 'The classic time — the lantern glows against the darkening river.' },
      { icon: 'cloud-rain', title: 'Misty mornings', text: 'Sunrise sessions in spring can include fog and softer light.' },
    ],
    tips: [
      { icon: 'clock', title: 'Arrive 30 minutes early', text: 'Set up before sunset so you do not miss the best light.' },
      { icon: 'sun', title: 'Bring a tripod', text: 'Essential for low-light photography of the lantern and birds.' },
      { icon: 'camera', title: 'Be respectful', text: 'Do not use flash, do not ask the fisherman to pose unnaturally, and tip if you are shooting commercially.' },
      { icon: 'utensils', title: 'Combine with dinner in Xingping', text: 'The town has good local restaurants — make an evening of it.' },
      { icon: 'droplet', title: 'Check weather and river levels', text: 'Heavy rain can make the river too fast or murky for fishing.' },
    ],
    gettingThere: [
      { t: 'Get to Xingping', d: 'Bus from Yangshuo (40 min, ¥15–20) or Guilin (2 hrs, ¥30–40).' },
      { t: 'Find the riverfront', d: 'Walk downhill from the bus stop toward the Li River.' },
      { t: 'Arrange a boat or tour', d: 'Ask at your hotel, a local cafe, or directly at the pier. Private boats are negotiable.' },
      { t: 'Return after dark', d: 'The last bus from Xingping to Yangshuo is usually around 19:00.' },
    ],
    tickets: [
      ['Private boat + cormorant demo', '¥150–400 — depends on group size and negotiation'],
      ['Photography tour', '¥300–800/person — guided session with arranged fisherman'],
      ['Bus to Xingping', '¥15–20 from Yangshuo · ¥30–40 from Guilin'],
      ['Best time', 'Sunset (around 6:30–7:30 PM in summer)'],
      ['Duration', '1–2 hours on the water'],
      ['Location', 'Xingping riverfront · Li River'],
    ],
    ticketNote: 'Prices are reference values and depend on negotiation. This is a cultural tradition, not a fixed show — availability varies. Always arrange through a local guide or hotel to support the community respectfully.',
    gallery: [
      { img: 'exp-cormorant', alt: 'Cormorant fisherman with lantern at dusk' },
      { img: 'exp-cormorant-1', alt: 'Trained cormorant catching fish' },
      { img: 'exp-cormorant-2', alt: 'Bamboo raft and traditional fishing gear' },
      { img: 'exp-cormorant-3', alt: 'Xingping riverfront at dusk' },
      { img: 'exp-cormorant-4', alt: 'Blue-hour photography of cormorant fishing' },
      { img: 'web-xingping-bend', alt: 'Li River karst peaks near Xingping' },
    ],
    faqs: [
      { q: 'Is cormorant fishing real, or just a show for tourists?', a: 'It is a real tradition, but today it survives mainly through tourism and photography. The fishermen are genuine practitioners who have worked with cormorants for generations. The best way to see it is to arrange a respectful private boat at sunset.' },
      { q: 'Where is the best place to see cormorant fishing?', a: 'Near Xingping, along the Li River. The Xingping riverfront is quieter and more traditional than the main Guilin piers.' },
      { q: 'Do the cormorants get hurt?', a: 'The birds are working animals with a long history of partnership with local fishermen. A traditional ring around the neck prevents them from swallowing large fish, but they are fed and cared for. Responsible tours prioritize the welfare of the birds and the fisherman.' },
      { q: 'What is the best time of day?', a: 'Sunset is the classic time — the lantern glows against the darkening river and karst peaks. Sunrise sessions are also beautiful and less crowded.' },
      { q: 'Can I take good photos without professional gear?', a: 'Yes, but a phone will struggle after sunset. A camera with a tripod or strong low-light performance is recommended for the lantern-lit scenes.' },
      { q: 'How much should I expect to pay?', a: 'A private boat with a cormorant demonstration usually costs ¥150–400 depending on group size and negotiation. Photography tours with guides are more expensive, around ¥300–800 per person.' },
    ],
    quickFacts: [
      ['Location', 'Li River near Xingping'],
      ['Duration', '1–2 hours'],
      ['Best time', 'Sunset'],
      ['Price range', '¥150–400'],
      ['Tradition', '1,000+ years'],
      ['Birds used', 'Trained cormorants'],
      ['Gear to bring', 'Tripod, camera, layers'],
    ],
    localTip: 'Do not treat the fisherman as a prop. Ask permission before taking close-up portraits, and consider buying a small print or tipping. This is a real person’s livelihood, not a theme park.',
    related: [
      { slug: 'li-river-cruise', img: 'exp-liriver', title: 'Li River Cruise', sub: 'Guilin → Yangshuo · Classic' },
      { slug: 'sunrise-viewpoint', img: 'exp-xianggong', title: 'Sunrise Viewpoint', sub: 'Xianggong Hill · Dawn' },
      { slug: 'xingping', img: 'attraction-xingping', title: 'Xingping Town', sub: 'Ancient town · 20-yuan view' },
    ],
    geo: { lat: 24.96, lng: 110.49 },
  },

  /* ============================== 5. BAMBOO RAFTING ============================== */
  {
    slug: 'bamboo-rafting',
    cardId: 'exp-bamboo',
    name: 'Bamboo Rafting',
    cnName: '遇龙河竹筏',
    kicker: 'Float the Quiet Yulong River on a Bamboo Raft',
    heroImage: 'exp-bamboo',
    ogImage: 'exp-bamboo',
    tagline: '遇龙河竹筏 · The Li River’s calmer, more intimate cousin',
    lead: 'Drift on a bamboo raft through clear, shallow water between bamboo groves and karst peaks — a slower, quieter way to see the Guilin countryside than the big cruise boats.',
    glance: '<strong class="text-river">Bamboo rafting on the Yulong River</strong> is the most peaceful way to experience the karst landscape. The rafts are poled by hand, the water is calm, and the only sounds are birds, bamboo, and the pole dipping into the river.',
    intro: [
      'The Yulong River is the smaller, gentler sister of the Li River. While the Li River cruise is grand and sweeping, the Yulong River is intimate and quiet. The traditional bamboo rafts here are long, narrow, and poled by a single boatman — no motor, no crowds, no hurry.',
      'The standard route runs from <strong class="text-river">Jinlong Bridge</strong> to <strong class="text-river">Old Xianyue Bridge</strong>, about 6 kilometers of slow drifting past water buffalo, farmers, and karst peaks reflected in the water. At the end, you can hop on a bike and pedal back to Yangshuo, or take a shuttle.',
      '<span class="text-sm text-stone-600"><em>Local tip: The first boats of the morning (around 8:00 AM) have the best light and the fewest tour groups. The river is often misty at this hour.</em></span>',
    ],
    highlights: [
      { img: 'exp-bamboo', title: 'Traditional Bamboo Raft', sub: '竹筏 · Pole-powered', text: 'A long raft of tied bamboo poles, poled by a boatman standing at the back — no engine noise, just the river.' },
      { img: 'exp-bamboo-1', title: 'Crystal-Clear Water', sub: '碧水 · See to the bottom', text: 'In many sections the water is so clear you can see pebbles, fish, and the reflection of the peaks above.' },
      { img: 'exp-bamboo-2', title: 'Bamboo Groves and Karst', sub: '竹林峰丛 · Green corridor', text: 'The river is lined with bamboo, banyan trees, and karst towers that feel close enough to touch.' },
      { img: 'exp-bamboo-3', title: 'Small Stone Bridges', sub: '古桥 · Crossings over the river', text: 'Old stone bridges span the Yulong at intervals, each one a photo opportunity and a piece of local history.' },
      { img: 'exp-bamboo-4', title: 'Water Buffalo and Riverside Life', sub: '田园 · Real countryside', text: 'Farmers wash vegetables, water buffalo cool off, and children play along the banks — life as it has been for centuries.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Jinlong Bridge to Old Xianyue Bridge', meta: '6 km · 1.5 hours · ¥160–320',
        steps: [
          { t: 'Get to Jinlong Bridge', d: 'By bike, e-bike, or taxi from Yangshuo (about 15 min).' },
          { t: 'Board a 2-person bamboo raft', d: 'Each raft holds two passengers plus the boatman.' },
          { t: 'Drift downstream', d: 'Pole-powered, about 6 km of quiet river and karst scenery.' },
          { t: 'Pass small rapids and weirs', d: 'Fun, gentle drops that get your feet wet — shoes off!'},
          { t: 'Arrive at Old Xianyue Bridge', d: 'Take the shuttle back or bike return to Yangshuo.' },
        ],
      },
      {
        icon: 'anchor', title: 'Short Section + Cycling Return', meta: '1 hour raft + 1 hour bike · ¥120–200 + bike rental',
        steps: [
          { t: 'Raft a shorter section', d: 'Choose the upstream half for a 1-hour drift.' },
          { t: 'Pick up a bike at the take-out', d: 'Arrange bike delivery in advance with your hotel.' },
          { t: 'Cycle back to Yangshuo', d: 'Flat, scenic riverside path — one of the best combos in Guilin.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'April – May', text: 'Warm, green, and often misty — the most romantic season.' },
      { icon: 'calendar-heart', title: 'September – November', text: 'Clear skies, calm water, and golden fields.' },
      { icon: 'sun', title: 'Early morning', text: '8:00 AM starts avoid the crowds and the midday heat.' },
    ],
    tips: [
      { icon: 'clock', title: 'Book the first raft', text: 'Morning light and fewer tourists make the experience much better.' },
      { icon: 'sun', title: 'Wear shoes you can get wet', text: 'The raft passes over small weirs; your feet will get wet. Sandals or water shoes are ideal.' },
      { icon: 'camera', title: 'Protect your camera', text: 'Water splashes happen. Use a waterproof case or keep your phone in a sealed bag.' },
      { icon: 'utensils', title: 'Bring small tips for the boatman', text: 'A small tip is appreciated, especially if they slow down for photos or explain the scenery.' },
      { icon: 'droplet', title: 'Check water levels', text: 'During drought, the route may be shortened. During floods, rafting may stop.' },
    ],
    gettingThere: [
      { t: 'Get to Yangshuo', d: 'From Guilin by bus (1.5 hrs) or after the Li River cruise.' },
      { t: 'Reach the put-in point', d: 'Jinlong Bridge is 15 minutes from Yangshuo by bike or taxi.' },
      { t: 'Buy tickets', d: 'Tickets can be bought at the pier or arranged through your hotel.' },
      { t: 'Return from the take-out', d: 'Shuttle bus or bike return to Yangshuo.' },
    ],
    tickets: [
      ['Full route (Jinlong → Xianyue)', '¥160–320 per raft — 2 passengers, 1.5 hours'],
      ['Short route', '¥120–200 per raft — 1 hour, 2 passengers'],
      ['Bike delivery to take-out', '¥20–30 — arrange with hotel'],
      ['Shuttle return', '¥10–20 per person'],
      ['Best time', '8:00–10:00 AM'],
      ['Raft capacity', '2 passengers + boatman'],
    ],
    ticketNote: 'Prices are reference values. Two-person rafts are standard. Solo travelers may need to share or pay for the whole raft. Bring cash — mobile payment may not work at the pier.',
    gallery: [
      { img: 'exp-bamboo', alt: 'Bamboo raft on the Yulong River' },
      { img: 'exp-bamboo-1', alt: 'Clear water reflecting karst peaks' },
      { img: 'exp-bamboo-2', alt: 'Bamboo groves along the Yulong River' },
      { img: 'exp-bamboo-3', alt: 'Stone bridge over the Yulong River' },
      { img: 'exp-bamboo-4', alt: 'Water buffalo along the riverbank' },
      { img: 'web-yulong-karst', alt: 'Aerial view of Yulong River valley' },
    ],
    faqs: [
      { q: 'Is the Yulong River bamboo raft worth it compared to the Li River cruise?', a: 'Yes — they are very different. The Li River cruise is grand and panoramic. The Yulong River raft is quiet, intimate, and hands-on. If you want calm water, no engine noise, and a closer view of village life, the Yulong raft is better.' },
      { q: 'How long is the bamboo raft ride?', a: 'The standard route from Jinlong Bridge to Old Xianyue Bridge is about 6 km and takes 1.5 hours. Shorter 1-hour sections are also available.' },
      { q: 'Do the rafts have motors?', a: 'No — the traditional Yulong River rafts are poled by hand by a boatman standing at the back. This is what makes the experience so peaceful.' },
      { q: 'Will I get wet?', a: 'Your feet will likely get wet, especially when the raft goes over small weirs. Wear sandals or water shoes. The rest of you should stay dry unless it splashes.' },
      { q: 'Can I do the raft one way and bike back?', a: 'Yes — this is a classic Yangshuo combo. Arrange bike delivery to the take-out point, then cycle back to town along the flat riverside path.' },
      { q: 'Do I need to book in advance?', a: 'In peak season (May, October) it is wise to book through your hotel. Off-season, you can usually buy tickets directly at the pier.' },
    ],
    quickFacts: [
      ['River', 'Yulong River'],
      ['Route length', '6 km'],
      ['Duration', '1–1.5 hours'],
      ['Best season', 'Apr–May · Sep–Nov'],
      ['Price', '¥160–320 per raft'],
      ['Capacity', '2 passengers'],
      ['Power', 'Pole-powered (no motor)'],
    ],
    localTip: 'Ask the boatman to go slowly. The default pace is leisurely, but if you want extra time for photos, a small tip (¥20–50) and a polite request usually work. Morning light on the water is magical.',
    related: [
      { slug: 'countryside-cycling', img: 'exp-cycling', title: 'Countryside Cycling', sub: 'Combine with rafting' },
      { slug: 'li-river-cruise', img: 'exp-liriver', title: 'Li River Cruise', sub: 'Bigger river panorama' },
      { slug: 'rock-climbing', img: 'exp-climb', title: 'Rock Climbing', sub: 'Yangshuo adventure' },
    ],
    geo: { lat: 24.79, lng: 110.48 },
  },

  /* ============================== 6. ROCK CLIMBING ============================== */
  {
    slug: 'rock-climbing',
    cardId: 'exp-climb',
    name: 'Rock Climbing',
    cnName: '阳朔攀岩',
    kicker: 'Scale World-Class Limestone Karst Towers in Yangshuo',
    heroImage: 'exp-climb',
    ogImage: 'exp-climb',
    tagline: '阳朔攀岩 · Asia’s best sport-climbing destination',
    lead: 'Yangshuo is one of the top sport-climbing destinations in Asia, with thousands of bolted routes on perfect limestone karst towers surrounded by rice fields and villages.',
    glance: '<strong class="text-river">Rock climbing in Yangshuo</strong> is the active traveler’s dream. The routes range from beginner-friendly to elite, the rock is high-quality limestone, and the scenery between climbs is as beautiful as the climbing itself.',
    intro: [
      'Yangshuo has been on the international climbing map since the 1990s, and for good reason. The karst towers here are made of compact, pocketed limestone with features that suit every style — crimps, tufas, roofs, and technical slabs. There are more than <strong class="text-river">300 bolted routes</strong> in the immediate area, and many more in the surrounding countryside.',
      'Whether you are a total beginner or a seasoned climber, Yangshuo has something for you. Beginner crags like <strong class="text-river">The Egg</strong> and <strong class="text-river">Swiss Cheese</strong> offer easy top-rope routes. Experienced climbers head to <strong class="text-river">Moon Hill</strong> for multi-pitch adventure or <strong class="text-river">White Mountain</strong> for hard sport lines.',
      '<span class="text-sm text-stone-600"><em>Local tip: The best seasons are spring and autumn. Summer is too hot and humid for most climbers, and winter can be surprisingly cold and damp in the shade.</em></span>',
    ],
    highlights: [
      { img: 'exp-climb', title: 'Limestone Karst Towers', sub: '石灰岩峰 · Perfect climbing rock', text: 'The same dramatic peaks that define Guilin’s landscape are also world-class climbing walls, with routes from 5.6 to 5.14.' },
      { img: 'exp-climb-1', title: 'The Egg Crag', sub: '鸡蛋山 · Beginner-friendly', text: 'A popular beginner and intermediate area with well-bolted routes, easy access, and beautiful views of the Yulong River valley.' },
      { img: 'exp-climb-2', title: 'Moon Hill', sub: '月亮山 · Multi-pitch arch', text: 'A natural moon-shaped arch in a karst tower, with classic multi-pitch routes climbing through and around it.' },
      { img: 'exp-climb-3', title: 'Climbing Community', sub: '岩友 · Global gathering', text: 'Yangshuo draws climbers from around the world. The town has gear shops, English-speaking guides, and a laid-back international vibe.' },
      { img: 'exp-climb-4', title: 'Rice-Field Views', sub: '稻田风景 · Climb with a view', text: 'Many crags are set right above rice paddies and villages — rest between routes with one of the best backdrops in Asia.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Beginner Half-Day at The Egg', meta: '4 hours · top-rope · ¥300–500',
        steps: [
          { t: 'Meet your guide in Yangshuo', d: 'Most guides provide harness, shoes, helmet, and chalk.' },
          { t: 'Drive to The Egg', d: '10 minutes from West Street by e-bike or car.' },
          { t: 'Learn basic safety', d: 'Belaying, knot tying, and falling safely.' },
          { t: 'Climb 3–4 routes', d: 'Easy top-rope routes from 5.6 to 5.9.' },
          { t: 'Return to Yangshuo', d: 'Optional dinner with the climbing community.' },
        ],
      },
      {
        icon: 'anchor', title: 'Moon Hill Multi-Pitch', meta: 'Half day · lead climbing · ¥600–1,000',
        steps: [
          { t: 'Meet early', d: 'Start around 7:30 AM to avoid heat and crowds.' },
          { t: 'Approach Moon Hill', d: 'Short hike to the base of the moon-shaped arch.' },
          { t: 'Climb 3–4 pitches', d: 'Classic routes up to 5.10+ with stunning views.' },
          { t: 'Rappel down', d: 'Descend through the arch for a memorable finish.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'March – May', text: 'Dry, warm, and sunny — ideal friction and comfortable cragging.' },
      { icon: 'calendar-heart', title: 'September – November', text: 'Cool mornings, warm afternoons, and stable weather.' },
      { icon: 'cloud-rain', title: 'Avoid summer midday', text: 'June–August is hot and humid; climb early morning or late afternoon.' },
    ],
    tips: [
      { icon: 'clock', title: 'Hire a local guide', text: 'A guide knows which crags are dry, which routes are safe, and how to avoid loose rock.' },
      { icon: 'sun', title: 'Climb early or late', text: 'Midday sun on limestone can be brutal. Morning and late afternoon sessions are more comfortable.' },
      { icon: 'camera', title: 'Protect your hands', text: 'Limestone is sharp. Bring tape and moisturize after climbing.' },
      { icon: 'utensils', title: 'Stay near West Street', text: 'Easy access to restaurants, gear shops, and climbing partners.' },
      { icon: 'droplet', title: 'Check for rain', text: 'Limestone stays damp after rain. Some crags dry faster than others — a guide can advise.' },
    ],
    gettingThere: [
      { t: 'Get to Yangshuo', d: 'From Guilin by bus (1.5 hrs) or after the Li River cruise.' },
      { t: 'Book a guide or rent gear', d: 'Climbing shops on West Street offer guide services, shoes, harnesses, and chalk bags.' },
      { t: 'Reach the crag', d: 'Most crags are 10–20 minutes from town by e-bike or car.' },
      { t: 'Return', d: 'Back to Yangshuo for showers and a well-earned meal.' },
    ],
    tickets: [
      ['Half-day guided climbing', '¥300–500/person — gear included, beginner crags'],
      ['Full-day guided climbing', '¥500–900/person — multi-pitch or hard sport routes'],
      ['Gear rental only', '¥100–200/day — shoes, harness, helmet, chalk'],
      ['Moon Hill entry', '¥15 — required to climb at Moon Hill'],
      ['Best seasons', 'Spring and autumn'],
      ['Route grades', '5.6 to 5.14'],
    ],
    ticketNote: 'Prices are reference values. Always climb with a partner or guide. Route conditions change after rain; check with local climbers before heading out.',
    gallery: [
      { img: 'exp-climb', alt: 'Rock climber on a Yangshuo karst tower' },
      { img: 'exp-climb-1', alt: 'The Egg climbing crag' },
      { img: 'exp-climb-2', alt: 'Moon Hill natural arch climb' },
      { img: 'exp-climb-3', alt: 'Climbing community in Yangshuo' },
      { img: 'exp-climb-4', alt: 'Rice field view from a climbing crag' },
      { img: 'web-yulong-karst', alt: 'Karst towers above the Yulong River' },
    ],
    faqs: [
      { q: 'Is Yangshuo good for beginner climbers?', a: 'Yes. Crags like The Egg and Swiss Cheese have many well-bolted, beginner-friendly routes. Local guides provide gear and instruction, so you can try climbing even if you have never done it before.' },
      { q: 'What grades are available?', a: 'Routes range from about 5.6 (beginner) to 5.14 (elite). There is something for every level, though the classic hard routes at White Mountain and Moon Hill attract advanced climbers from around the world.' },
      { q: 'Do I need to bring my own gear?', a: 'No. Climbing shops and guides in Yangshuo rent shoes, harnesses, helmets, and chalk. Experienced lead climbers may prefer to bring their own rope and quickdraws.' },
      { q: 'When is the best time to climb?', a: 'Spring (March–May) and autumn (September–November) are ideal. Summer is hot and humid; winter can be cold and damp, especially in the shade of the crags.' },
      { q: 'Is it safe?', a: 'Yes, with a guide and proper equipment. Limestone can have loose rock, so local knowledge matters. Always check recent route conditions and avoid climbing right after heavy rain.' },
      { q: 'Can I combine climbing with other activities?', a: 'Absolutely. Many climbers raft the Yulong River or cycle the countryside on rest days. Yangshuo is compact, so you can mix active days easily.' },
    ],
    quickFacts: [
      ['Location', 'Yangshuo'],
      ['Rock type', 'Limestone karst'],
      ['Route count', '300+ bolted routes'],
      ['Grades', '5.6 to 5.14'],
      ['Best seasons', 'Spring · Autumn'],
      ['Half-day guide', '¥300–500'],
      ['Famous crags', 'The Egg · Moon Hill · White Mountain'],
    ],
    localTip: 'Even if you do not climb, watching the sunset from the base of Moon Hill with a cold beer is one of Yangshuo’s most underrated experiences. The climbers silhouetted against the orange sky make it feel like a movie scene.',
    related: [
      { slug: 'countryside-cycling', img: 'exp-cycling', title: 'Countryside Cycling', sub: 'Rest-day activity' },
      { slug: 'bamboo-rafting', img: 'exp-bamboo', title: 'Bamboo Rafting', sub: 'Cool off after climbing' },
      { slug: 'sunrise-viewpoint', img: 'exp-xianggong', title: 'Sunrise Viewpoint', sub: 'Earned rest day view' },
    ],
    geo: { lat: 24.78, lng: 110.49 },
  },

  /* ============================== 7. COOKING CLASS ============================== */
  {
    slug: 'cooking-class',
    cardId: 'exp-cook',
    name: 'Cooking Class',
    cnName: '桂林烹饪课',
    kicker: 'Shop Local Markets and Cook Guilin Classics with English-Speaking Chefs',
    heroImage: 'exp-cook',
    ogImage: 'exp-cook',
    tagline: '桂林烹饪课 · Beer fish, rice noodles, and the stories behind them',
    lead: 'Start at a local market, learn to choose the freshest ingredients, then cook Guilin classics like beer fish, chili-stuffed tofu, and rice noodles in a hands-on class led by English-speaking local chefs.',
    glance: '<strong class="text-river">A Guilin cooking class</strong> is more than a recipe lesson — it is a window into daily life. You visit the market, meet vendors, taste snacks, and learn why Guilin food tastes the way it does.',
    intro: [
      'Guilin’s food is shaped by its rivers, mountains, and climate. The dishes are fresh, slightly spicy, and heavy on river fish, rice, bamboo, and pickled vegetables. A cooking class lets you understand those ingredients from the source — starting at the market where locals buy them every morning.',
      'Most classes in Yangshuo begin with a market tour, followed by hands-on cooking of 3–4 dishes. The classics usually include <strong class="text-river">Yangshuo beer fish</strong> (啤酒鱼), <strong class="text-river">Guilin rice noodles</strong> (桂林米粉), <strong class="text-river">stuffed tofu</strong> (酿豆腐), and a seasonal vegetable stir-fry. At the end, you sit down and eat everything you made.',
      '<span class="text-sm text-stone-600"><em>Local tip: Ask your instructor to show you how to make chili oil and pickled bamboo shoots — they are the secret behind Guilin’s signature flavors and easy to recreate at home.</em></span>',
    ],
    highlights: [
      { img: 'exp-cook', title: 'Local Market Tour', sub: '菜市场 · Ingredients first', text: 'Walk through stalls of fresh fish, river snails, tofu, chilies, and morning-picked vegetables while your teacher explains what to look for.' },
      { img: 'exp-cook-1', title: 'Yangshuo Beer Fish', sub: '啤酒鱼 · The local star', text: 'A whole river fish braised in beer with tomatoes, chilies, and garlic — the dish every Yangshuo restaurant claims to make best.' },
      { img: 'exp-cook-2', title: 'Guilin Rice Noodles', sub: '桂林米粉 · Breakfast of champions', text: 'Learn to make the broth, prepare the toppings, and assemble a bowl of the city’s most beloved breakfast.' },
      { img: 'exp-cook-3', title: 'Stuffed Tofu and Vegetables', sub: '酿豆腐 · Hakka-influenced', text: 'A technique of filling tofu, peppers, and eggplant with minced pork and herbs — a staple in local home cooking.' },
      { img: 'exp-cook-4', title: 'Eat What You Cook', sub: '共享午餐 · The reward', text: 'After class, sit down with your fellow cooks and enjoy the meal you prepared, paired with local tea or rice wine.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Morning Market + Cooking Class', meta: '3–4 hours · Yangshuo · ¥250–450',
        steps: [
          { t: 'Meet at the market', d: 'Usually around 9:00 AM before the best produce sells out.' },
          { t: 'Market tour', d: 'Learn to choose fish, tofu, vegetables, and spices.' },
          { t: 'Cook 3–4 dishes', d: 'Beer fish, rice noodles, stuffed tofu, and a seasonal vegetable.' },
          { t: 'Sit down to eat', d: 'Enjoy your lunch with tea and conversation.' },
          { t: 'Take home recipes', d: 'Most instructors give you printed recipes in English.' },
        ],
      },
      {
        icon: 'anchor', title: 'Evening Dumpling & Noodle Class', meta: '2 hours · dinner class · ¥200–350',
        steps: [
          { t: 'Meet at the cooking school', d: 'Late afternoon, around 4:30 PM.' },
          { t: 'Make dumplings from scratch', d: 'Wrapping, folding, and two classic dipping sauces.' },
          { t: 'Cook rice noodles', d: 'Guilin-style with pickled beans, peanuts, and chili oil.' },
          { t: 'Eat dinner together', d: 'A relaxed end to a day of exploring.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'Year-round', text: 'Cooking classes run in all seasons.' },
      { icon: 'sun', title: 'Morning classes', text: 'Morning market tours are the freshest and most authentic.' },
      { icon: 'calendar-check', title: 'Book 1 day ahead', text: 'Small classes fill up quickly, especially in peak season.' },
    ],
    tips: [
      { icon: 'clock', title: 'Come hungry', text: 'You will eat a full meal at the end of class. Skip breakfast or plan a light one.' },
      { icon: 'sun', title: 'Wear casual clothes', text: 'Aprons are provided, but avoid anything you would mind smelling like garlic and chili oil.' },
      { icon: 'camera', title: 'Take notes and photos', text: 'The recipes are simple, but the techniques are worth remembering.' },
      { icon: 'utensils', title: 'Mention dietary restrictions', text: 'Vegetarian, vegan, and halal options are usually available if requested when booking.' },
      { icon: 'droplet', title: 'Bring a reusable bag', text: 'Useful for carrying market purchases or recipe printouts.' },
    ],
    gettingThere: [
      { t: 'Get to Yangshuo', d: 'From Guilin by bus (1.5 hrs) or after the Li River cruise.' },
      { t: 'Book a class', d: 'Reserve through your hotel, a cooking school on West Street, or online.' },
      { t: 'Meet at the market or school', d: 'Your confirmation will include the meeting point and time.' },
      { t: 'Enjoy your meal', d: 'Classes usually end with a shared lunch or dinner.' },
    ],
    tickets: [
      ['Market tour + cooking class', '¥250–450/person — 3–4 hours, 3–4 dishes'],
      ['Evening dumpling/noodle class', '¥200–350/person — 2 hours, dinner included'],
      ['Private class', '¥500–800/person — customized menu, flexible timing'],
      ['Class size', 'Small groups (2–8 people)'],
      ['Includes', 'Ingredients, apron, recipes, meal'],
      ['Best time', 'Morning (9:00 AM) for market tour'],
    ],
    ticketNote: 'Prices are reference values. Most classes include all ingredients, an apron, and printed recipes. Dietary restrictions should be communicated when booking.',
    gallery: [
      { img: 'exp-cook', alt: 'Cooking class ingredients in Yangshuo' },
      { img: 'exp-cook-1', alt: 'Yangshuo beer fish being prepared' },
      { img: 'exp-cook-2', alt: 'Guilin rice noodles bowl' },
      { img: 'exp-cook-3', alt: 'Stuffed tofu and vegetables' },
      { img: 'exp-cook-4', alt: 'Shared meal after cooking class' },
      { img: 'food-chunji', alt: 'Local Guilin restaurant dish' },
    ],
    faqs: [
      { q: 'Do I need cooking experience?', a: 'No. Classes are designed for all levels. The instructor demonstrates each step, and you cook at your own station with help when needed.' },
      { q: 'What dishes will I learn?', a: 'Most classes teach Yangshuo beer fish, Guilin rice noodles, stuffed tofu or eggplant, and a seasonal vegetable dish. Some schools offer customized menus.' },
      { q: 'Is the market tour included?', a: 'Yes, in most morning classes. You visit a local market to buy ingredients and learn about regional produce before returning to cook.' },
      { q: 'Can vegetarians or people with allergies join?', a: 'Yes, but you should mention dietary needs when booking. Many schools can adapt recipes to be vegetarian, vegan, or halal.' },
      { q: 'How long is a typical class?', a: 'Morning market + cooking classes last 3–4 hours. Evening focused classes (dumplings, noodles) are usually 2 hours.' },
      { q: 'Will I get the recipes?', a: 'Yes, most schools provide printed English recipes so you can recreate the dishes at home.' },
    ],
    quickFacts: [
      ['Location', 'Yangshuo'],
      ['Duration', '2–4 hours'],
      ['Class size', '2–8 people'],
      ['Price range', '¥200–450'],
      ['Includes', 'Market tour · ingredients · meal · recipes'],
      ['Signature dishes', 'Beer fish · rice noodles · stuffed tofu'],
      ['Dietary options', 'Vegetarian / vegan / halal on request'],
    ],
    localTip: 'Do not just make the beer fish — ask the instructor to explain the sauce. The combination of beer, tomato, chili, and garlic is the base of many local dishes. Once you understand it, you can cook dozens of Guilin-style meals at home.',
    related: [
      { slug: 'countryside-cycling', img: 'exp-cycling', title: 'Countryside Cycling', sub: 'Work off the meal' },
      { slug: 'bamboo-rafting', img: 'exp-bamboo', title: 'Bamboo Rafting', sub: 'Afternoon activity' },
      { slug: 'li-river-cruise', img: 'exp-liriver', title: 'Li River Cruise', sub: 'Morning before class' },
    ],
    geo: { lat: 24.78, lng: 110.49 },
  },

  /* ============================== 8. SUNRISE VIEWPOINT ============================== */
  {
    slug: 'sunrise-viewpoint',
    cardId: 'exp-xianggong',
    name: 'Sunrise Viewpoint',
    cnName: '相公山日出',
    kicker: 'Climb Xianggong Mountain for the Best Sunrise View in Guilin',
    heroImage: 'exp-xianggong',
    ogImage: 'exp-xianggong',
    tagline: '相公山日出 · The viewpoint that makes photographers cry',
    lead: 'A 30-minute climb in the dark leads to a panoramic platform above the Li River, where sunrise lights a sea of karst towers and river mist — the single most spectacular dawn view in Guilin.',
    glance: '<strong class="text-river">Xianggong Mountain</strong> (相公山) offers the best elevated viewpoint of the Li River. The short but steep climb is rewarded with a 360-degree view of the river bending through dozens of karst peaks, often wrapped in morning fog.',
    intro: [
      'There are many viewpoints around Guilin, but Xianggong Mountain is the one that photographers and local guides agree on. From the summit, the Li River appears as a silver ribbon below, coiling between rows of limestone towers that stretch into the distance. On clear mornings, the light turns the peaks gold. On misty mornings, the valleys fill with fog and the towers become islands in a white sea.',
      'The climb is about <strong class="text-river">30–40 minutes</strong> on stone steps, mostly shaded. It is steep but manageable for anyone with reasonable fitness. Most visitors arrive at the trailhead in the dark, around 5:00 AM, to be on top before dawn.',
      '<span class="text-sm text-stone-600"><em>Local tip: Bring a headlamp, warm layers, and a tripod. The summit platform gets crowded during peak season; arriving early secures the best spot.</em></span>',
    ],
    highlights: [
      { img: 'exp-xianggong', title: 'Summit Panorama', sub: '相公山顶 · 360° view', text: 'The Li River bends through a corridor of karst peaks, with layers of mountains fading into the distance.' },
      { img: 'exp-xianggong-1', title: 'Sea of Clouds', sub: '云海 · Mist in the valleys', text: 'After rain or on humid mornings, the valleys fill with fog and the peaks float like islands.' },
      { img: 'exp-xianggong-2', title: 'Golden Dawn Light', sub: '金色日出 · First light', text: 'For a few minutes after sunrise, the limestone towers glow warm orange and gold before the light turns flat.' },
      { img: 'exp-xianggong-3', title: 'The Li River Ribbon', sub: '漓江丝带 · Silver water', text: 'From above, the river looks like a thin silver ribbon winding between the mountains.' },
      { img: 'exp-xianggong-4', title: 'Photography Platform', sub: '观景台 · Built for cameras', text: 'The summit has several viewing platforms at different angles, designed to give photographers clean sightlines.' },
    ],
    routes: [
      {
        icon: 'ship', title: 'Sunrise from Xianggong Mountain', meta: '3–4 hours total · 30-min climb · ¥150–300',
        steps: [
          { t: 'Leave Yangshuo or Guilin before 5:00 AM', d: 'Private transfer or sunrise tour is easiest.' },
          { t: 'Arrive at the trailhead', d: 'The gate opens early; buy your ticket.' },
          { t: 'Climb 30–40 minutes', d: 'Stone steps, mostly shaded and steep.' },
          { t: 'Set up on the platform', d: 'Choose your angle before the sky brightens.' },
          { t: 'Watch sunrise and return', d: 'Most people head down by 7:30 AM for breakfast.' },
        ],
      },
      {
        icon: 'anchor', title: 'Combine with Li River Cruise Day', meta: 'Full day · active · flexible cost',
        steps: [
          { t: 'Sunrise at Xianggong', d: 'Start the day with the best view.' },
          { t: 'Descend and transfer to Xingping', d: 'About 30 minutes by car.' },
          { t: 'Take the bamboo raft', d: 'See the river from water level.' },
          { t: 'Explore Xingping town', d: 'Breakfast, old street, and the 20-yuan view.' },
        ],
      },
    ],
    bestTime: [
      { icon: 'calendar-heart', title: 'April – May', text: 'Misty mornings and lush green hills — the classic photo season.' },
      { icon: 'calendar-heart', title: 'September – November', text: 'Clear skies and golden light; fog is less common but views are crisp.' },
      { icon: 'cloud-rain', title: 'After rain', text: 'The best chance for a dramatic sea of clouds the next morning.' },
    ],
    tips: [
      { icon: 'clock', title: 'Arrive 45 minutes before sunrise', text: 'You need time to climb and set up before the sky brightens.' },
      { icon: 'sun', title: 'Bring warm layers', text: 'The summit can be windy and cold before dawn, even in summer.' },
      { icon: 'camera', title: 'Headlamp and tripod', text: 'The climb starts in darkness. A tripod is essential for long exposures.' },
      { icon: 'utensils', title: 'Eat after, not before', text: 'A light snack before the climb is fine, but plan a proper breakfast back in town.' },
      { icon: 'droplet', title: 'Check the weather', text: 'Fog can block the view, but it also creates the most beautiful sea-of-clouds shots.' },
    ],
    gettingThere: [
      { t: 'From Yangshuo', d: 'Private car or sunrise tour (40 min, ¥150–300 per tour).' },
      { t: 'From Guilin', d: 'About 1.5 hours by car; sunrise tours can pick you up at your hotel.' },
      { t: 'Buy the entry ticket', d: '¥60 at the trailhead gate.' },
      { t: 'Climb to the summit', d: '30–40 minutes of stone steps.' },
    ],
    tickets: [
      ['Entry ticket', '¥60 — paid at the trailhead gate'],
      ['Sunrise tour from Yangshuo', '¥150–300/person — includes transport and ticket'],
      ['Private car from Guilin', '¥400–600 — more flexible for photographers'],
      ['Climb time', '30–40 minutes'],
      ['Best months', 'April–May, September–November'],
      ['Sunrise time', '6:00–7:00 AM depending on season'],
    ],
    ticketNote: 'Prices are reference values. The entry ticket is paid at the gate. Sunrise tours are the easiest option because they handle transport and timing in the dark.',
    gallery: [
      { img: 'exp-xianggong', alt: 'Xianggong Mountain sunrise panorama' },
      { img: 'exp-xianggong-1', alt: 'Sea of clouds over the Li River valley' },
      { img: 'exp-xianggong-2', alt: 'Golden dawn light on karst peaks' },
      { img: 'exp-xianggong-3', alt: 'Li River seen from Xianggong Mountain' },
      { img: 'exp-xianggong-4', alt: 'Photography platform at the summit' },
      { img: 'web-xingping-bend', alt: 'Karst peaks of the Li River near Xingping' },
    ],
    faqs: [
      { q: 'How hard is the climb to Xianggong Mountain?', a: 'It is a steep 30–40 minute climb on stone steps. Most people with reasonable fitness can do it, but it is not wheelchair accessible and may be challenging for those with knee issues.' },
      { q: 'Is it worth it if the weather is cloudy?', a: 'Yes — but for different reasons. Clear skies give crisp views. Fog and low clouds create the famous sea-of-clouds effect. The only disappointing weather is heavy rain or thick, low fog that blocks everything.' },
      { q: 'What time do I need to leave?', a: 'From Yangshuo, leave around 4:30–5:00 AM to arrive at the trailhead, climb, and set up before sunrise. From Guilin, leave earlier, around 4:00 AM.' },
      { q: 'Can I go without a tour?', a: 'Yes, if you have a private car or driver. There is no public bus at that hour. Many travelers join a sunrise tour for convenience.' },
      { q: 'What should I bring?', a: 'A headlamp, warm layers, a tripod, camera, water, and a small snack. Good shoes with grip are important for the stone steps.' },
      { q: 'Is it crowded?', a: 'During peak seasons (May and October) the summit platform can be busy. Arrive early and be patient. Off-season, you may have the view almost to yourself.' },
    ],
    quickFacts: [
      ['Location', 'Xianggong Mountain, near Xingping'],
      ['Elevation', '~300 m above the river'],
      ['Climb time', '30–40 minutes'],
      ['Entry fee', '¥60'],
      ['Best time', 'Sunrise'],
      ['Best months', 'Apr–May · Sep–Nov'],
      ['View', 'Li River + karst peaks'],
    ],
    localTip: 'If the summit is crowded, move to the lower platform on the left. It has a slightly different angle of the Li River bend and is often less packed. The photo is just as good.',
    related: [
      { slug: 'li-river-cruise', img: 'exp-liriver', title: 'Li River Cruise', sub: 'See the river from below' },
      { slug: 'cormorant-fishing', img: 'exp-cormorant', title: 'Cormorant Fishing', sub: 'Sunset on the same river' },
      { slug: 'xingping', img: 'attraction-xingping', title: 'Xingping Town', sub: 'Nearby ancient town' },
    ],
    geo: { lat: 25.05, lng: 110.45 },
  },
];
